[14.0][MIG] Module stock_picking_invoicing
OCA/account-invoicing pull request #1014
Opened 2021-10-07 18:47 UTC by mbcosta

Migration module stock_picking_invoicing to v14, the PR https://github.com/OCA/account-invoicing/pull/1010 are missing the last commits made in v13:

![image](https://user-images.githubusercontent.com/6341149/136444169-b7df92be-b129-44b8-babd-e6d07e224eea.png)

cc @rvalyi @renatonlima @mileo @zar21

2021-11-05 15:38 UTC, hparfr commented on stock_picking_invoicing/wizards/stock_invoice_onshipping.py
> +        """Ungrup your moves, split them again, grouping by
Ungroup

2021-11-05 15:39 UTC, hparfr commented on stock_picking_invoicing/wizards/stock_invoice_onshipping.py
> +        """Ungrup your moves, split them again, grouping by
```suggestion
        """Ungroup your moves, split them again, grouping by
```

2021-11-05 15:40 UTC, hparfr commented on stock_picking_invoicing/wizards/stock_invoice_onshipping.py
> +        """Overrite this metothod if you need to change any values of the
Override

2021-11-05 16:21 UTC, rvalyi commented on stock_picking_invoicing/wizards/stock_invoice_onshipping.py
> +        """Overrite this metothod if you need to change any values of the
metothod -> method

2021-11-12 09:57 UTC, hildickethan approved these changes

2021-11-12 15:02 UTC, rvalyi requested changes
Hello @mbcosta 

1. this commit seems an error: when removing such decorators, methods become @api.multi by default. Something there are not as they work on the RecordSet Model and not a recordset itself (look at other default_get declarations in other modules) https://github.com/OCA/account-invoicing/pull/1014/commits/f7662ba33dc86cbae0036b1f025806b222fd41cf
2. contributors are not expected to re-generate REAME files in specific commits such as https://github.com/OCA/account-invoicing/pull/1014/commits/6773f416d7fe48392f4ae70a32b252c677f3c2a9 as these are re-generated by the OCA bots anyway. So better if you remove that commit too.
3. Once this commit is removed it's better if you squash https://github.com/OCA/account-invoicing/pull/1014/commits/4fe918a17f9bad6e729c169158d8ccde4ec989da onto the previous migration commit because such trivial code formating commits don't deserve dedicated commit (it pollutes the log).

Use `rebase -i` for this cleanup. The othercommits are OK.

2021-11-12 17:35 UTC, rvalyi approved these changes

2021-11-12 18:27 UTC, rvalyi commented
/ocabot merge nobump

2021-11-12 18:39 UTC, merged

2021-11-12 18:52 UTC, mbcosta commented
Thanks all for reviews, the PRs https://github.com/OCA/account-invoicing/pull/1010 and https://github.com/OCA/account-invoicing/pull/800 should be closed after this merge.

2021-11-12 19:22 UTC, rvalyi commented
> Thanks all for reviews, the PRs #1010 and #800 should be closed after this merge.

Done!