[14.0][ADD] account_move_line_accounting_description
OCA/account-invoicing pull request #1021
Opened 2021-10-15 15:25 UTC by ajaniszewska-dev

2021-10-19 13:15 UTC, ajaniszewska-dev commented on account_move_line_accounting_description_purchase/tests/test_purchase_order_description.py
> +        self.assertEqual(self.po_1_line.name, self.product_1.accounting_description)
@grindtildeath  assertion is failing here, what did i missed? tried to put pdb in` _prepare_account_move_line()` and it seems to not be called at all.

```
 File "/home/travis/build/OCA/account-invoicing/setup/account_move_line_accounting_description_purchase/odoo/addons/account_move_line_accounting_description_purchase/tests/test_purchase_order_description.py", line 68, in test_purchase_order_line_name

    self.assertEqual(self.po_1_line.name, self.product_1.accounting_description)

AssertionError: 'Virtual Interior Design' != 'Product1_acc_desc'

- Virtual Interior Design

+ Product1_acc_desc
```

2021-10-20 14:11 UTC, grindtildeath commented on account_move_line_accounting_description_purchase/tests/test_purchase_order_description.py
> +        self.assertEqual(self.po_1_line.name, self.product_1.accounting_description)
@ajaniszewska-dev `_prepare_account_move_line` is called when you generate the vendor bill from the PO. And only on the `account.move.line` we want the accounting description to be used for name, not on `purchase.order.line` :wink:

2021-10-21 12:15 UTC, yankinmax approved these changes

2021-10-21 13:21 UTC, grindtildeath requested changes
- The change in invoice report (to use `external_name` instead of `name` is missing)
- Could you add a test for the onchange in account_move_line_accounting_description? Tip: Use Form class in tests instead of `create` to simulate the UI (it also plays onchange functions automatically)

2021-10-21 13:21 UTC, grindtildeath commented on account_move_line_accounting_description/models/account_move.py
> +from odoo import api, fields, models
Missing header (on many other files too)

2021-10-21 13:21 UTC, grindtildeath commented on account_move_line_accounting_description_sale/__manifest__.py
> +    "summary": "Adds an 'accounting description' on sale order",
```suggestion
    "summary": "Consider accounting description when invoicing sale order",
```

2021-10-21 13:21 UTC, grindtildeath commented on account_move_line_accounting_description_sale/__manifest__.py
> +    "data": [],
You could remove empty key and set module as auto install. (also for the glue to purchase module)

2021-10-21 13:21 UTC, grindtildeath commented on account_move_line_accounting_description_sale/models/sale_order.py
> +        line = super(SaleOrderLine, self)._prepare_invoice_line(**optional_values)
```suggestion
        line = super()._prepare_invoice_line(**optional_values)
```
You don't need this in py3 ;)

2021-10-21 13:21 UTC, grindtildeath commented on account_move_line_accounting_description_sale/models/sale_order.py
> +        product = self.env["product.product"].search([("id", "=", line["product_id"])])
```suggestion
        product_id = line.get("product_id")
        if product_id:
            product = self.env["product.product"].browse(line["product_id"])
```
`browse` is better than `search` if you already have the id.
Also if the line is a note or a section `line["product_id"]` might throw a `KeyError` here.

2021-10-21 13:21 UTC, grindtildeath commented on account_move_line_accounting_description_purchase/models/purchase_order.py
> +            res["name"] = product.accounting_description
Same as above or below ;)

2021-10-21 13:21 UTC, grindtildeath commented on account_move_line_accounting_description_purchase/__manifest__.py
> +    "summary": "Adds an 'accounting description' on purchase order",
To fix (cf suggestion for other module)

2021-10-21 13:21 UTC, grindtildeath commented on account_move_line_accounting_description/views/account_move.xml
> +            </xpath>
Could you also set the name column invisible for invoice line view?

2021-10-22 08:01 UTC, ajaniszewska-dev commented on account_move_line_accounting_description/views/account_move.xml
> +            </xpath>
@grindtildeath thanks, PR updated with your remarks.

2021-10-24 16:36 UTC, ajaniszewska-dev commented on account_move_line_accounting_description/tests/test_account_move_line_description.py
> +        # )
@grindtildeath  any idea why `external_name` is `False` in test? (In UI it is properly set to product's name when changing product so I'd expect same here). Due to that, test is failing - same with l.71-73.

2021-10-28 09:06 UTC, grindtildeath commented on account_move_line_accounting_description/tests/test_account_move_line_description.py
> +        # )
I would say, check with a pdb in your onchange. Ff the `name` is set to `accounting_description` if means your onchange must be played and there's probably a `False` value in the `name` beforehand on this line: `line.external_name = line.name`?

2021-10-28 09:09 UTC, grindtildeath commented on account_move_line_accounting_description/tests/test_account_move_line_description.py
> +        cls.product_2 = cls.env.ref("product.product_product_2")
The test would be much easier to read if you call your variables for what you expect (e.g. `cls.product_with_acc_desc` and `cls.product_without_acc_desc`) :wink:

2021-10-28 14:24 UTC, ajaniszewska-dev commented on account_move_line_accounting_description/tests/test_account_move_line_description.py
> +        # )
@grindtildeath  it wasnt saved after saving form, that's why. Changed field to related to product_id.name instead - seems to be working fine. No idea why form didnt save this field normally.

2021-10-28 16:28 UTC, grindtildeath commented
@ajaniszewska-dev Please check https://github.com/ajaniszewska-dev/account-invoicing/pull/1

2021-10-29 09:06 UTC, grindtildeath approved these changes

2021-11-05 15:17 UTC, kittiu commented
@ajaniszewska-dev
Can you provide a decent readme for each module? 
Thanks!

2021-11-16 03:50 UTC, kittiu commented
/ocabot merge nobump

2021-11-16 07:31 UTC, merged