[MIG] account_invoice_pricelist_sale: Migration to 15.0
OCA/account-invoicing pull request #1092
Opened 2022-02-02 14:17 UTC by nicomacr

2022-02-07 15:27 UTC, ajaniszewska-dev commented on account_invoice_pricelist_sale/readme/DESCRIPTION.rst
> +and Copies pricelist from sales order to invoice.s
```suggestion
and Copies pricelist from sales order to invoices
```

2022-02-07 15:28 UTC, ajaniszewska-dev commented
@nicomacr  tests are failing, pls check it.

2022-02-14 15:19 UTC, ajaniszewska-dev commented on account_invoice_pricelist_sale/__manifest__.py
> +    "depends": ["account_invoice_pricelist", "sale"],
pls check if this module (account_invoice_pricelist) is already migrated, it looks it fails because it cannot be found in required version.

2022-03-30 15:09 UTC, nicomacr commented
waiting this PR [#1111](https://github.com/OCA/account-invoicing/pull/1111)

2022-06-30 10:56 UTC, marylla commented
Hi @nicomacr Could you please rebase? Currently I cannot test it on runboat...

2022-11-29 10:06 UTC, fkantelberg requested changes
Please rebase on the current 15.0 branch. This should fix the CI. Otherwise it works locally.

2022-11-30 16:02 UTC, navarrorico commented
Works fine for me, functional review :+1:

2022-12-21 14:25 UTC, grindtildeath approved these changes

2022-12-21 14:26 UTC, grindtildeath commented
/ocabot migration account_invoice_pricelist_sale

2022-12-21 14:35 UTC, grindtildeath commented
@nicomacr Can you please rebase?

2022-12-21 19:26 UTC, nicomacr commented
> @nicomacr Can you please rebase?

Done!

2022-12-22 08:19 UTC, marylla approved these changes
I made a functional review in runboat.
It works fine. The pricelist is passed from sale order to invoice.

2022-12-27 10:57 UTC, jabelchi approved these changes
Functional test is working for me.
Tested on runboat

2023-01-03 08:38 UTC, hildickethan-S73 approved these changes

2023-01-03 17:34 UTC, grindtildeath commented on account_invoice_pricelist_sale/__manifest__.py
> +    "version": "15.0.1.0.1",
```suggestion
    "version": "15.0.1.0.0",
```
Can you please commit this change?

2023-01-04 12:55 UTC, grindtildeath commented
/ocabot merge nobump

2023-01-04 13:06 UTC, merged