[15.0][MIG] account_invoice_force_number
OCA/account-invoicing pull request #1170
Opened 2022-06-04 21:41 UTC by JuanyDForgeflow

This module allows to force the invoice numbering. It displays the move_name field.
If user fills that field, the typed value will be used as invoice (and move) number.
Otherwise, the next sequence number will be retrieved and saved.
So, the new field has to be used when user doesn't want to use the default invoice numbering for a specific invoice.

2022-06-29 10:19 UTC, MiquelRForgeFlow commented
please rebase

2022-06-30 12:26 UTC, JuanyDForgeflow commented
> please rebase

Done!

2022-06-30 12:26 UTC, JuanyDForgeflow commented
> please rebase

Done!

2022-06-30 12:55 UTC, MiquelRForgeFlow requested changes

2022-06-30 12:55 UTC, MiquelRForgeFlow commented on account_invoice_force_number/__manifest__.py
> +    "version": "15.0.1.0.1",
```suggestion
    "version": "15.0.1.0.0",
```

2022-10-12 00:21 UTC, JuanyDForgeflow commented on account_invoice_force_number/__manifest__.py
> +    "version": "15.0.1.0.1",
@MiquelRForgeFlow done

2022-10-12 20:49 UTC, MiquelRForgeFlow approved these changes

2023-01-12 15:33 UTC, andreampiovesana approved these changes
Tested in production

2023-01-19 14:01 UTC, FSchiepers commented
Hi,
I tested the module and I always get the following error:
The Date (01/19/2023) doesn't match the sequence number of the related Journal Entry (INV/2022-12-007)
You will need to clear the Journal Entry's Number to proceed.
In doing so, you might want to resequence your entries in order to maintain a continuous date-based sequence.

2023-06-07 11:45 UTC, AaronHForgeFlow commented
Hi @FSchiepers , Can you reproduce the issue in runboat?

2023-06-07 11:55 UTC, AaronHForgeFlow approved these changes
Functional tests

2023-06-23 15:37 UTC, kaynnan approved these changes

2023-06-26 13:59 UTC, AaronHForgeFlow commented
/ocabot merge nobump

2023-06-26 14:13 UTC, merged