[14.0][MIG] account_invoice_line_sequence
OCA/account-invoicing pull request #1174
Opened 2022-06-13 04:07 UTC by JuanyDForgeflow

Provides a new sequence field on invoice lines which helps to manage the order of the invoice lines.

The sequence number always starts at 1 and rises incrementally: 1, 2, 3, ... To keep it that way, all sequence numbers are recalculated when the order of invoice lines is changed. The line number is printed on the invoice report.

2022-06-15 06:45 UTC, andreampiovesana approved these changes
go

2022-06-20 09:11 UTC, matteoopenf approved these changes

2022-06-20 17:39 UTC, andreampiovesana approved these changes
merge?

2022-06-20 17:40 UTC, matteoopenf commented
@OCA/accounting-maintainers

2022-07-15 10:38 UTC, MiquelRForgeFlow requested changes

2022-07-15 10:38 UTC, MiquelRForgeFlow commented on account_invoice_line_sequence/models/account_move.py
> +    sequence_show = fields.Integer(
this is wrong, don't rename it. it's intended to rewrite the original sequence field.

2022-07-15 10:38 UTC, MiquelRForgeFlow commented on account_invoice_line_sequence/models/account_move.py
> +        help="Shows the sequence of this line in the " " invoice.",
```suggestion
        help="Shows the sequence of this line in the invoice.",
```
please, do this in all the cases where it happens

2022-07-15 13:31 UTC, MiquelRForgeFlow commented on account_invoice_line_sequence/readme/CONTRIBUTORS.rst
> +* Eficent Business and IT Consulting Services S.L. <contact@eficent.com>
😅

2022-07-15 15:19 UTC, MiquelRForgeFlow approved these changes

2022-07-15 17:24 UTC, AaronHForgeFlow approved these changes
Functional review, it looks good, including the printout

2022-07-15 17:25 UTC, AaronHForgeFlow commented
/ocabot merge nobump

2022-07-15 17:34 UTC, merged