[ADD]invoice_discount_display_amount: Show total discount on invoices
OCA/account-invoicing pull request #1179
Opened 2022-06-16 09:48 UTC by manuelregidor

This module shows the total discount amount and the amount without discount on invoices.

2022-06-16 09:50 UTC, manuelregidor commented
@HaraldPanten @ValentinVinagre

2022-06-16 10:57 UTC, ValentinVinagre requested changes

2022-06-16 10:57 UTC, ValentinVinagre commented on invoice_discount_display_amount/models/account_move_line.py
> +        for line in self:
You should only take into account those that are invoice lines

2022-06-16 10:59 UTC, ValentinVinagre commented on invoice_discount_display_amount/models/account_move_line.py
> +            if not line.discount:
can be added as a filtered in the for and make a massive change to those that are not invoice lines and do not have a discount

2022-06-16 11:00 UTC, ValentinVinagre commented on invoice_discount_display_amount/models/account_move.py
> +        for invoice in self:
you should filter those account.move that are not invoices and directly indicate that the value of the fields is 0.0 with a massive change.

2022-06-16 14:56 UTC, ValentinVinagre approved these changes
👯‍♂️

2022-06-16 14:56 UTC, ValentinVinagre commented
@HaraldPanten could you review?

2022-06-16 15:15 UTC, HaraldPanten approved these changes
Functional review

2022-06-16 15:31 UTC, ValentinVinagre commented
@AaronHForgeFlow could you review?

2022-06-20 14:41 UTC, HaraldPanten commented
/ocabot merge nobump

2022-06-20 14:54 UTC, merged