[15.0][mig] account_invoice_blocking
OCA/account-invoicing pull request #1265
Opened 2022-10-17 05:39 UTC by JordiBForgeFlow

Standard migration

2022-10-18 10:18 UTC, PieterPaulussen requested changes
A few conventions that can be easily applied, otherwise this looks good to me.

2022-10-18 10:18 UTC, PieterPaulussen commented on account_invoice_blocking/models/account_move.py
> +class AccountInvoice(models.Model):
Perhaps a more suitable name would be 
```suggestion
class AccountMove(models.Model):
```

2022-10-18 10:18 UTC, PieterPaulussen commented on account_invoice_blocking/models/account_move.py
> +    blocked = fields.Boolean(
I believe this field is best defined right below the models' private attributes like `_inherit` instead of at the bottom of the file.

2022-10-18 10:18 UTC, PieterPaulussen commented on account_invoice_blocking/views/account_move.xml
> +    <record id="account_invoice_form_view" model="ir.ui.view">
```suggestion
    <record id="view_move_form" model="ir.ui.view">
```

2022-10-19 19:22 UTC, adrienpeiffer approved these changes

2022-10-26 05:12 UTC, JordiBForgeFlow commented
@PieterPaulussen thanks for your feedback. I have applied your suggestions.

2022-10-26 07:56 UTC, PieterPaulussen approved these changes

2022-10-26 10:35 UTC, JordiBForgeFlow commented
/ocabot migration account_invoice_blocking
/ocabot merge nobump

2022-10-26 10:44 UTC, merged