[13.0][MIG] account invoice refund reason: Migration to 13
OCA/account-invoicing pull request #1268
Opened 2022-10-19 14:32 UTC by JaumeBforgeFlow

2022-10-19 14:40 UTC, JuanyDForgeflow commented on account_invoice_refund_reason/tests/test_account_invoice_refund_reason.py
> +                move_type="out_invoice",
change to type

2022-10-19 14:42 UTC, MiquelRForgeFlow commented
Add commit history please.

2022-10-19 15:24 UTC, JaumeBforgeFlow commented
@MiquelRForgeFlow  @JuanyDForgeflow fixed!

2022-10-19 15:36 UTC, MiquelRForgeFlow commented on account_invoice_refund_reason/tests/test_account_invoice_refund_reason.py
> +                date_mode="custom",
```suggestion
                date="custom",
```

2022-10-19 15:36 UTC, MiquelRForgeFlow commented on account_invoice_refund_reason/i18n/es.po
> +"Project-Id-Version: Odoo Server 14.0+e\n"
```suggestion
"Project-Id-Version: Odoo Server 13.0+e\n"
```

2022-10-20 06:31 UTC, GuillemCForgeFlow requested changes

2022-10-20 06:31 UTC, GuillemCForgeFlow commented on account_invoice_refund_reason/wizard/account_move_reversal.py
> +        "account.invoice.refund.reason", string="Reason to credit"
```suggestion
        "account.invoice.refund.reason", string="Refund Reason"
```
Perhaps using the same name in the wizard as the one in the view just to not confuse the user.

2022-10-20 07:27 UTC, JaumeBforgeFlow commented
@GuillemCForgeFlow @MiquelRForgeFlow Fixed!

2022-10-20 08:13 UTC, MiquelRForgeFlow approved these changes

2022-10-20 08:23 UTC, GuillemCForgeFlow approved these changes
:+1:

2022-10-20 11:03 UTC, JordiMForgeFlow approved these changes
Code + functional review 👍🏼

2022-10-20 12:34 UTC, AaronHForgeFlow approved these changes

2022-10-20 12:35 UTC, AaronHForgeFlow commented
/ocabot merge nobump

2022-10-20 12:50 UTC, merged