[16.0][MIG] account_invoice_date_due: Migration to 16.0
OCA/account-invoicing pull request #1447
Opened 2023-04-25 09:02 UTC by smussie

2023-04-27 07:42 UTC, leemannd commented on account_invoice_date_due/tests/test_account_invoice_date_due.py
> +                "user_type_id": cls.env.ref("account.data_account_type_receivable").id,
AFAIR: the field has been replaced by `account_type` and in this case the value should be `asset_receivable`

2023-05-09 22:03 UTC, RodrigoBM commented
@smussie  change de name PR to [16.0][MIG] account_invoice_date_due: Migration to 16.0

2023-05-19 13:40 UTC, santostelmo commented
@smussie from 15.0 to 16.0 the field `invoice_date_due` became computed. That changes the way we can assert permissions to write on the field via `Form`. 
[v15](
https://github.com/odoo/odoo/blob/c63cd2f0140959a7ac6e05ef15ac5c2ac552453d/addons/account/models/account_move.py#L308) vs [v16](https://github.com/odoo/odoo/blob/0ba04dc5b2c002e6e7d43fd1342fc159623948b6/addons/account/models/account_move.py#LL265C5-L265C21)

I changed the code to control the rights of the user to write on the field `invoice_date_due` on the backend. This is now done via inverse compute method  `_inverse_invoice_date_due`.

2023-06-09 07:37 UTC, Gelo-fl approved these changes
Functional review OK https://www.awesomescreenshot.com/video/18177465?key=0b3be688c705df9c840a25c91c816258

2023-06-14 09:13 UTC, leemannd approved these changes

2023-06-22 10:01 UTC, JavierIniesta commented
Hi @smussie 

Please could you take into account these two steps from the migration wiki? (https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0)

- Check https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests for a procedure for reducing commits from "OCA Transbot...".
- Add tests to increase code coverage.

2023-08-09 00:02 UTC, michaelslade54 commented
Functional review OK.

2023-08-09 13:50 UTC, rafaelbn commented
/ocabot migration account_invoice_date_due

2023-08-09 13:52 UTC, rafaelbn commented
Hello @smussie !

Thank you for this migration, in order to get it meged please attend @JavierIniesta comments in

https://github.com/OCA/account-invoicing/pull/1447#issuecomment-1602360825

> Hi @smussie
> 
> Please could you take into account these two steps from the migration wiki? (https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0)
> 
>     Check https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests for a procedure for reducing commits from "OCA Transbot...".
>     Add tests to increase code coverage.
>

2023-08-17 08:49 UTC, santostelmo commented on account_invoice_date_due/models/account_move.py
> +        if self.env.context.get("bypass_compute_amount"):
I tried to write a unit test for better coverage in order to check if super  `_compute_amount` is called when invoice's due date is updated.
I did some functional testing and indeed the method is not called. 
When I look at the  dependencies of ` _compute_amount` I don't see any related with `invoice_date_due`  https://github.com/odoo/odoo/blob/a6f8d9c512ffb816e18bb43a5efa510707877cf6/addons/account/models/account_move.py#L833
The variable `bypass_compute_amount` seems to not be required

2023-08-18 08:04 UTC, ipconinpe approved these changes

2023-08-18 08:23 UTC, ipconinpe commented
Hi,
When you change invoice date due,  it works correctly and it changes the account move lines Date Due,
But when you reset the invoice to draft and you confirm it again, the account move lines date due doesnt update.

[Grabación de pantalla desde 2023-08-18 10-21-05.webm](https://github.com/OCA/account-invoicing/assets/121874127/29045100-6f8c-4703-b14a-2a880f78b1cd)

2023-10-13 14:51 UTC, josep-tecnativa commented
Please, include this changes https://github.com/OCA/account-invoicing/pull/1576/commits/9511a9f06be41edfe17c0fbcae87e62e3e45c605

2023-12-14 11:42 UTC, ljsalvatierra-factorlibre commented
Hii @smussie could you please update this?

2024-02-07 08:28 UTC, sleyvenn commented
Hello, is there any news about this?

2024-03-14 10:25 UTC, sleyvenn commented
@smussie ??

2024-03-21 16:03 UTC, RodrigoBM commented
@smussie ??

2024-03-25 08:31 UTC, gurneyalex commented
I'm taking this over. I just squashed the translation commits, and I'll include https://github.com/OCA/account-invoicing/commit/9511a9f06be41edfe17c0fbcae87e62e3e45c605 later today.

2024-03-26 00:12 UTC, gurneyalex commented
@ipconinpe my last commit on this PR fixes your issue.

2024-03-26 08:29 UTC, santostelmo reviewed
[FIX] handle resetting the invoice to Draft LG
About unit tests falling I am not sure there is any relation

2024-03-26 09:05 UTC, santostelmo approved these changes

2024-03-26 12:06 UTC, gurneyalex commented
I'll check the tests (they are green on my computer :-/ )

2024-03-26 22:16 UTC, gurneyalex commented
the issue with reset to draft seems to be an odoo issue, and the workaround i tried has nasty side effects -> i'm dropping it for now.

What I found is that in the sync_dynamic_line context manager during the call to button_draft, we get here https://github.com/odoo/odoo/blob/01197ebdfa0f2930fa058e95af624eccc06ac2ab/addons/account/models/account_move.py#L2104

-> the needed_after and needed_before are identical -> no further processing is done. 

However the existing_before and existing_after are different and the date_maturity in existing_after is different from the one in needed_after -> I would expect the code to fix things in this case. 

I'm lost...

2024-04-10 12:27 UTC, andreampiovesana commented
merge?

2024-04-15 11:48 UTC, BT-anieto commented
merge?

2024-04-15 12:18 UTC, pedrobaeza commented
@gurneyalex is it OK for you?

2024-08-01 06:49 UTC, etobella commented
/ocabot rebase

2024-08-01 07:19 UTC, etobella commented
@gurneyalex How do you want to proceed with the problem found? Maybe we can the issue in the ROADMAP and continue with the merge?

2024-09-27 07:17 UTC, sergiobstoj commented
@gurneyalex is this OK for merge?

2024-09-27 08:10 UTC, andreampiovesana commented
merge?

2024-10-18 10:53 UTC, anmarmo1 commented
can it be merged?

2024-10-23 09:23 UTC, zamberjo approved these changes
LGTM

2024-10-23 09:23 UTC, zamberjo commented
@gurneyalex @etobella is it possible to merge?

2024-10-23 09:42 UTC, etobella commented
@gurneyalex Can you help us with this?

@simahawk

2024-11-07 14:15 UTC, ljsalvatierra-factorlibre requested changes

2024-11-07 14:15 UTC, ljsalvatierra-factorlibre commented on account_invoice_date_due/models/account_move.py
> +        if "invoice_date_due" in vals and self.state == "posted":
```
ValueError

Expected singleton: account.move(1756941, 1749387)
```

2024-11-12 08:44 UTC, ljsalvatierra-factorlibre requested changes

2024-11-12 08:44 UTC, ljsalvatierra-factorlibre commented on account_invoice_date_due/models/account_move.py
> +            )
```suggestion
        posted_moves = self.filtered(lambda x: x.state == "posted")
        if "invoice_date_due" in vals and 0 < len(posted_moves):
            payment_term_lines = posted_moves.line_ids.filtered(
                lambda line: line.account_id.account_type
                in ("asset_receivable", "liability_payable")
            )
```

2025-02-20 12:23 UTC, aaladro-kernet commented
Hello, correct functional test in my flow.
what's about merge?

2025-03-20 09:34 UTC, sergiobstoj commented
merge?

2025-03-20 10:44 UTC, simahawk commented
Sorry, I missed previous notifications and @smussie is not with us anymore :innocent: 

/ocabot merge nobump

2025-03-20 11:01 UTC, merged