[16.0][mig] account_invoice_search_by_reference: Migration to 16.0
OCA/account-invoicing pull request #1455
Opened 2023-05-09 13:18 UTC by dsolanki-initos

2023-05-13 08:28 UTC, pedrobaeza commented
/ocabot migration account_invoice_search_by_reference

2023-06-07 11:25 UTC, hildickethan-S73 commented on account_invoice_search_by_reference/models/account_move.py
> +        return invoices.name_get()
this should already be covered by core `_rec_names_search = ['name', 'partner_id.name', 'ref']`

2023-06-07 14:12 UTC, SoniaViciana commented
This module maybe it's not necessary as long as you can configure [base_name_search_improved](https://github.com/OCA/server-tools/pull/2477)

2023-06-07 15:43 UTC, AaronHForgeFlow commented
That other module seems very interesting. But searching invoices by reference is so common that I think this one is still useful. If you only want to improve this specific search this modules is much light than the other one, that is more useful for more complex cases.

2023-11-23 08:58 UTC, legalsylvain commented
Hi @dsolanki-initos. Your branch is conflicting. could you take a look ?

2024-01-30 15:24 UTC, legalsylvain requested changes
AFAIK, the feature is native in odoo ``account`` module in V16.
https://github.com/OCA/OpenUpgrade/pull/4288
https://github.com/odoo/odoo/pull/103400/files

CC : original author : @AaronHForgeFlow, @nikul-serpentcs (v10), @bjeficent (v12) , @newtratip (v13), @chusamo (v14) , @koenloodts (v15)

2024-01-30 15:41 UTC, AaronHForgeFlow commented
@legalsylvain thanks for the clarification, I think we can close this

2024-01-30 15:41 UTC, closed without merging