[16.0][MIG] account invoice fixed discount
OCA/account-invoicing pull request #1481
Opened 2023-06-10 18:26 UTC by TITUS6304658

16.0 mig account invoice fixed discount

Migration to version 15.0

2023-07-24 08:28 UTC, CRogos requested changes
Please reaname the module in your PR subject to account_invoice_fixed_discount.

There is also a second PR ongoing here. https://github.com/OCA/account-invoicing/pull/1488

2023-07-24 08:28 UTC, CRogos commented on account_invoice_fixed_discount/tests/test_account_fixed_discount.py
> -        self.assertEqual(invoice.invoice_line_ids.price_subtotal, 100.00)
Why did you remove these tests? There is no test left in this file.

2023-07-24 08:38 UTC, rousseldenis commented
@TITUS6304658 @CRogos In fact, the module has to be refactored due to core changes. See https://github.com/OCA/account-invoicing/pull/1488#issuecomment-1647462394 comments.

Tests are passing but in fact... not tested.

2023-07-24 08:39 UTC, rousseldenis requested changes
To be refactored or superseded by #1488

2023-08-03 21:21 UTC, rafaelbn commented
/ocabot migration account_invoice_fixed_discount

2023-08-03 21:23 UTC, rafaelbn commented
superseded by https://github.com/OCA/account-invoicing/pull/1488

2023-08-03 21:23 UTC, closed without merging