[16.0][MIG] account_invoice_fixed_discount: Migration to 16.0
OCA/account-invoicing pull request #1488
Opened 2023-06-19 14:48 UTC by PieterPaulussen

2023-07-20 13:06 UTC, CRogos commented
@PieterPaulussen are you still working on this migration?

2023-07-20 13:14 UTC, PieterPaulussen commented
@CRogos Hi, sorry, left this PR a bit hanging at the moment. There are a few fixes that still need to be applied to the code. If you want, you can fork the repo and apply the fixes. I'll see if I can do it later this evening myself otherwise.

2023-07-20 13:29 UTC, CRogos commented
Thank you for the quick response. If you can do it in the near future, I'll happy to wait. Contact me if you need some help or when you are ready for review.

2023-07-23 17:45 UTC, FrancoMaxime requested changes

2023-07-23 17:45 UTC, FrancoMaxime commented on account_invoice_fixed_discount/models/account_move_line.py
> +class AccountMove(models.Model):
I think it would be better to split the file into two. The first for account_move and the second for account_move_line

2023-07-23 17:45 UTC, FrancoMaxime commented on account_invoice_fixed_discount/views/account_move_view.xml
> -            <xpath
Why do you remove this?

2023-07-23 17:45 UTC, FrancoMaxime commented on account_invoice_fixed_discount/tests/test_account_fixed_discount.py
> +class TestInvoiceFixedDiscount(SavepointCase):
SavepointCase class is now deprecated, you should use TransactionCase instead.

2023-07-23 17:45 UTC, FrancoMaxime commented
Thanks for contributing @PieterPaulussen

2023-07-24 07:59 UTC, rousseldenis commented
@PieterPaulussen This is a duplicate as there is already #1481

2023-07-24 08:24 UTC, CRogos commented
Thx for the link to the other PR. Didn't find it,  too. But the test of the other PR are only green, because the were all deleted. Nevertheless there is some good changes which can be added here, too.

2023-07-24 08:33 UTC, PieterPaulussen commented
@rousseldenis @CRogos I believe the other PR is insufficient. I'm testing the module locally for the migration and noticed that most of the upstream methods do not exist at all. So all the `super()` calls there seem faulty. They are also not tested using a `Form` which is suboptimal but only visible during a manual test.

The implementation of the price fields has completely changed in V16.0 compared to the last version of this module by refactoring all the fields to computed fields with inverse onchanges.

My interpretation of the module is that this serves as a 'convenience' module to the user to give explicit discounts. Therefor I'm going to suggest to change the implementation. By reverse calculating the discount percentage per line when setting the `fixed_discount` and then relying on the core to apply the appropriate downstream logic to update the `discount` and `price_unit` fields.

Any thoughts on that?

2023-07-24 08:36 UTC, rousseldenis commented
> @rousseldenis @CRogos I believe the other PR is insufficient. I'm testing the module locally for the migration and noticed that most of the upstream methods do not exist at all. So all the `super()` calls there seem faulty. They are also not tested using a `Form` which is suboptimal but only visible during a manual test.
> 
> The implementation of the price fields has completely changed in V16.0 compared to the last version of this module by refactoring all the fields to computed fields with inverse onchanges.
> 
> My interpretation of the module is that this serves as a 'convenience' module to the user to give explicit discounts. Therefor I'm going to suggest to change the implementation. By reverse calculating the discount percentage per line when setting the `fixed_discount` and then relying on the core to apply the appropriate downstream logic to update the `discount` and `price_unit` fields.
> 
> Any thoughts on that?

Indeed, I've just saw that.

A refactoring is needed. You take care of that ?

2023-07-24 08:37 UTC, PieterPaulussen commented
@rousseldenis working on it now 👍

2023-08-03 21:22 UTC, rafaelbn commented
/ocabot migration account_invoice_fixed_discount

2023-08-03 21:24 UTC, rafaelbn commented
/ocabot migration account_invoice_fixed_discount

2023-08-03 21:35 UTC, rafaelbn commented
Did you follow up the FIX in 14? 

https://github.com/OCA/account-invoicing/pull/1225

2023-08-09 16:54 UTC, CRogos requested changes
The merge of discount_fixed with discount has another side effect when resetting a discount to 0.
[video (12).webm](https://github.com/OCA/account-invoicing/assets/1799080/cad8b9c3-3624-4ac9-ae6e-da8dc5772ce2)

2023-08-10 08:31 UTC, PieterPaulussen commented
> Did you follow up the FIX in 14?
> 
> #1225

@CRogos I've checked the case described in the [PR](https://github.com/OCA/account-invoicing/pull/1225) and the original case from the [ticket](https://github.com/OCA/account-invoicing/issues/1107). I believe my changes to the implementation do not require tax recalculation, but I have implemented the required `float_round` and `float_compare`. 
Because the implementation "steers" the value of the discount field making ensuring the tax is always updated accordingly. It is always the core `discount` field value that is used instead of having a separate field which should be taken into account in other calculations.


> The merge of discount_fixed with discount has another side effect when resetting a discount to 0. [video (12).webm](https://github.com/OCA/account-invoicing/assets/1799080/cad8b9c3-3624-4ac9-ae6e-da8dc5772ce2)

I've also checked this and it was the last if block of the onchange which circumvented the update of the discount field. That should be fixed now.

2023-08-10 08:46 UTC, CRogos approved these changes
Code + functional test LGTM.

2023-08-10 08:51 UTC, CRogos reviewed
Sorry, found one more thing which is not 100% perfect.

Can you update discount_fixed, when it is != 0 and the discount field is updated?

[video (13).webm](https://github.com/OCA/account-invoicing/assets/1799080/c6d6c88e-91dc-490e-ab49-f92ccba47bf8)

2023-08-10 09:03 UTC, PieterPaulussen commented
> Sorry, found one more thing which is not 100% perfect.
> 
> Can you update discount_fixed, when it is != 0 and the discount field is updated?
> 
>  video.13.webm

Fixed in latest update.

2023-08-10 09:29 UTC, CRogos commented
It is now updated when you set the dicount field to 0, but if you change it from 10% to 20% it stays on 75€
![image](https://github.com/OCA/account-invoicing/assets/1799080/2d0f8f9a-b142-4bce-90a0-831513d98fd6)

2023-08-10 10:23 UTC, PieterPaulussen commented
@CRogos Same issue here as with the `sale_fixed_discount` regarding the onchanges. I've applied the same onchange context values here in order to support the workflow.

2023-08-10 10:57 UTC, PieterPaulussen commented
Great the tests are botched now because of the onchanges. Apparently the O2MForm class does not support inserting context values. I'll have to think of something else.

2023-08-10 11:26 UTC, CRogos commented
oh no... I really appreciate all the effort you've already put here. 

Have you tried to make discount_fixed a computed attribute (non stored) with an inverse function setting discount?

2023-08-10 15:09 UTC, CRogos commented on account_invoice_fixed_discount/reports/report_account_invoice.xml
> +        </xpath>
We already talked about to combine the value in the PDF. I would prefer this.
![image](https://github.com/OCA/account-invoicing/assets/1799080/6f08158f-b34b-4761-835f-b0758c20b301)

2023-08-11 11:48 UTC, PieterPaulussen commented
@CRogos Another update for this module. I've refactored it to improve the usability and now the expected workflow should be supported. Had to dig deep into the tax calculation of Odoo to account for the rounding differences (similar to the behavior of the `sale_fixed_discount` module. Feel free to try it again.

2023-08-21 11:56 UTC, CRogos commented
@PieterPaulussen here are still the issues like in the sale https://github.com/OCA/sale-workflow/pull/2614

- Setting the discount to fixed 32€ changes the discount to 10%, but changing it back to 0, leaves the discount to 10%
- In the PDF layout Fixed discount and % are not merged into 1 column as it is now in sale

2023-08-22 07:27 UTC, PieterPaulussen commented
> @PieterPaulussen here are still the issues like in the sale [OCA/sale-workflow#2614](https://github.com/OCA/sale-workflow/pull/2614)
> 
> * Setting the discount to fixed 32€ changes the discount to 10%, but changing it back to 0, leaves the discount to 10%
> * In the PDF layout Fixed discount and % are not merged into 1 column as it is now in sale

@CRogos Sorry, I made the changes to the code but never pushed it. You can re-test it now.

2023-08-22 11:49 UTC, CRogos commented
Yes can confirm it is working. 

I discovered one small difference between invoice and quotation. In one PDF we have the currency, in the other it is missing. Not sure which is the better solution, but I think it should be implemented the same.

![image](https://github.com/OCA/account-invoicing/assets/1799080/b128a7d4-fd9c-4608-a8d6-979996abbceb)
![image](https://github.com/OCA/account-invoicing/assets/1799080/83010f61-1cd0-4b6b-bc02-7556c09ea3a7)

2023-08-30 07:43 UTC, rousseldenis approved these changes

2023-09-07 16:00 UTC, CRogos commented
@pedrobaeza I think this can be merged.

2023-09-07 16:03 UTC, pedrobaeza commented
OK, merging blindly due to reviews:

/ocabot merge nobump

2023-09-07 16:14 UTC, merged