[8.0] add account_invoice_product_supplier_price_update
OCA/account-invoicing pull request #155
Opened 2016-05-25 09:14 UTC by chafique-delli

This module allow from the supplier invoice, to automatic update all products whose unit price on the line is different from the supplier price.
This P.R. depends to OCA/product-variant#19

2016-05-26 04:00 UTC, elicoidal commented on account_invoice_product_supplier_price_update/README.rst
> +help us smashing it by providing a detailed and welcomed `feedback
You can simplify this part with the newest template

2016-05-26 04:02 UTC, elicoidal commented on account_invoice_product_supplier_price_update/__openerp__.py
> +    'summary': 'From the supplier invoice, to automatic update all products '
In the supplier invoice, automatically update all products 
whose unit price on the line is different from the supplier price

2016-05-26 04:02 UTC, elicoidal commented on account_invoice_product_supplier_price_update/__openerp__.py
> +    'installable': True,
probably not necessary as this is the default one

2016-05-26 08:11 UTC, chafique-delli commented
@elicoidal , thank you for the code review, I fixed this.

2016-06-07 12:27 UTC, eLBati commented on account_invoice_product_supplier_price_update/README.rst
> +It created a new supplier price if there is not or it updates the first.
```created``` --> ```creates```

2016-06-07 12:33 UTC, chafique-delli commented
@eLBati , thank you for the code review, I fixed this.

2016-06-07 12:40 UTC, pedrobaeza commented on account_invoice_product_supplier_price_update/README.rst
> +This module allow in the supplier invoice, automatically update all products
s/allow/allows

2016-06-07 12:40 UTC, pedrobaeza commented on account_invoice_product_supplier_price_update/README.rst
> +This module allow in the supplier invoice, automatically update all products
s/, automatically/, to automatically

2016-06-07 12:41 UTC, pedrobaeza commented on account_invoice_product_supplier_price_update/__openerp__.py
> +        'product_variant_supplierinfo',
This module and the following are not real dependencies. Just conveniences, but the module will work the same, except for that features.

2016-06-07 12:42 UTC, pedrobaeza commented on account_invoice_product_supplier_price_update/__openerp__.py
> +        'purchase',
purchase is not needed for having product.supplierinfo. They are in the product module.

2016-06-07 13:43 UTC, chafique-delli commented on account_invoice_product_supplier_price_update/__openerp__.py
> +        'product_variant_supplierinfo',
@pedrobaeza ,  thank you for the code review.
Indeed, the dependencies on the modules 'purchase' and 'product_variant_supplierinfo' are not necessary.

2016-06-07 13:45 UTC, pedrobaeza commented on account_invoice_product_supplier_price_update/__openerp__.py
> +        'product_variant_supplierinfo',
And you don't need also `product_supplierinfo_tree_price_info`

2016-06-07 13:51 UTC, chafique-delli commented on account_invoice_product_supplier_price_update/__openerp__.py
> +        'product_variant_supplierinfo',
@pedrobaeza ,in my code, I use the field 'unit_price note' of 'product.supplierinfo' which comes from the module 'product_supplierinfo_tree_price_info'.

2016-06-07 15:18 UTC, pedrobaeza commented on account_invoice_product_supplier_price_update/__openerp__.py
> +        'product_variant_supplierinfo',
But that module is only for displaying information in an human readable form, not for using for another purposes. I would say to not using anything from this module.

2016-06-09 08:04 UTC, chafique-delli commented
Travis test is red because the test of  'account_invoice_merge_purchase' module failed.

2016-07-26 10:13 UTC, sebastienbeau commented on account_invoice_product_supplier_price_update/account_invoice.py
> +                ('product_tmpl_id', '=', line.product_id.product_tmpl_id.id),
you must depend on this module to get the right supplier https://github.com/OCA/product-variant/pull/32

2016-07-26 10:20 UTC, sebastienbeau commented
@chafique-delli can you fis the way to get the right supplier and add a test with
- a specific supplier (a supplier info attach to one variant)
- a generic supplier (a supplier info attach to the template => all variant)

2016-09-22 10:30 UTC, sebastienbeau commented on account_invoice_product_supplier_price_update/account_invoice.py
> +            current_price_unit = [(6, 0, [])]
The code can be more simple here.
- first the current_price_unit do not need the 6, 0 as you always use the [0][2] after so you can remove it.
- then you do not need all of the variable suppinfo...

`
something like that:

    def _check_product_supplierprice(self):                         
    lines = []                                                             
    for line in self.invoice_line:                                         
        current_price_unit = []
        supplier = self.partner_id.commercial_partner_id or self.partner_id
	suppinfo = False
        current_price_uni = []
        for seller in line.product_id.seller_ids:                          
            if supplier == seller.name: 
                suppinfo = seller
                current_price_unit = [pricelist.price for p in suppinfo.pricelist_ids]
                break                                                      
        if line.price_unit not in current_price_unit:                                               
            lines.append((0, 0, {                                          
                'name': line.name,                                         
                'current_price_unit': suppinfo.unit_price_note,            
                'new_price_unit': line.price_unit,                         
                'suppinfo_id': suppinfo.id,                                
                'to_variant': True,                                        
                'supplier_id': supplier_id.id,                             
                'product_id': line.product_id.id,                          
                'product_tmpl_id': line.product_id.product_tmpl_id.id,     
            }))                                                            
    return lines                                                           
`

2016-09-22 10:45 UTC, sebastienbeau commented on account_invoice_product_supplier_price_update/wizard/supplier_invoice_update_product_supplier_price.py
> +class SupplierinvoiceUpdateProductSupplierpriceLine(models.TransientModel):
can you found a shorter class name?

2016-09-22 10:46 UTC, sebastienbeau commented on account_invoice_product_supplier_price_update/wizard/supplier_invoice_update_product_supplier_price.py
> +                line.suppinfo_id = self.env['product.supplierinfo'].create(
can you avoid the repetition of self.env['product.supplierinfo'] by creating a variable called supinfo_obj ?

2016-09-22 10:47 UTC, sebastienbeau commented on account_invoice_product_supplier_price_update/wizard/supplier_invoice_update_product_supplier_price.py
> +class SupplierinvoiceUpdateProductSupplierprice(models.TransientModel):
can you find a shorter class name?

2016-09-22 10:47 UTC, sebastienbeau requested changes
Some code simplification should be done

2016-09-22 13:05 UTC, sebastienbeau reviewed
split test

2016-09-22 13:05 UTC, sebastienbeau commented on account_invoice_product_supplier_price_update/tests/test_supplier_invoice_update_product_supplier_price.py
> +class TestSupplierInvoiceUpdateProductSupplierPrice(TransactionCase):
We should split the test in 3 as there is 3 test on 3 invoice

2016-10-14 10:51 UTC, sebastienbeau commented on account_invoice_product_supplier_price_update/tests/test_update_supplier_price.py
> +        invoice_7 = self.env.ref(
Can you split the test ? one per invoice

2016-10-17 09:45 UTC, chafique-delli commented
@gurneyalex, Is you can watch why the runbot test shows me this error:
except_orm: ('Error', u"You try to install module 'account_invoice_product_supplier_price_update' that depends on module 'product_variant_supplierinfo'.\nBut the latter module is not available in your system.")
While the file 'oca_dependencies.txt' contains' product-variant' repository which contains  product_variant_supplierinfo' module.
Thank you.

2016-10-26 12:07 UTC, gurneyalex commented
@chafique-delli runbot should be fixed now.

2016-10-31 10:09 UTC, chafique-delli commented
@gurneyalex , thank you for the fix on runbot, but is you can watch why the travis test shows an error on installing the  account_invoice_merge_purchase module whereas,  a priori my  account_invoice_product_supplier_price_update module is not installed yet.

2016-11-07 10:52 UTC, gurneyalex commented
@chafique-delli this is not your fault. The 8.0 branch build is red on Travis (https://travis-ci.org/OCA/account-invoicing/jobs/166920774)

2016-11-14 13:11 UTC, legalsylvain requested changes
Hi, @chafique-delli. Some remarks inline.  2 others below. Just a code review for the time being, I'll test it functionaly and more deeply friday.

Otherwise, thanks a lot to share this work !
For shops it is a "must have feature".
- Not sure the image module will help people to understand what the module makes. Default OCA module should be better ? (not a blocking point for me).
- Not sure to have understand all the workflow stuff : invoice validation... (but I just do a quick code review, I'll take a time friday).

2016-11-14 13:11 UTC, legalsylvain commented on account_invoice_product_supplier_price_update/wizard/update_supplier_price.py
> +        invoice.signal_workflow('invoice_open')
Why do you launch this workflow ?

2016-11-14 13:11 UTC, legalsylvain commented on account_invoice_product_supplier_price_update/wizard/update_supplier_price.py
> +        invoice = self.env['account.invoice'].browse(
self.ensure_one() is required if you do not manage a for each wizard in self.

2016-11-14 13:11 UTC, legalsylvain commented on account_invoice_product_supplier_price_update/wizard/update_supplier_price.py
> +                vals = {
maybe calling default value function could allow to have different user defined default value ? (not sure about that point, just a question).

2016-11-14 13:11 UTC, legalsylvain commented on account_invoice_product_supplier_price_update/__openerp__.py
> +        'product_variant_supplierinfo'
Hi. I understand why you depend on this module, but for me, the feature should work if product_variant_supplierinfo is not installed.
What about to split the module in two : 
-  account_invoice_product_supplier_price_update that will depends on account only and work with generic feature
- account_invoice_variant_product_supplier_price_update that will depends on 'product_variant_supplierinfo' and 'account_invoice_product_supplier_price_update', managing variants specifics, overloading function.

If people are agree with that point, I can help you for that refactoring.

2016-11-14 13:11 UTC, legalsylvain commented on account_invoice_product_supplier_price_update/__openerp__.py
> +        'product_supplierinfo_tree_price_info',
I don't see why you depend on this module. (even if this module is cool ;-) )

2016-11-14 13:11 UTC, legalsylvain commented on account_invoice_product_supplier_price_update/__openerp__.py
> +        'demo/account_invoice_demo.xml',
could you git mv for
- demo/product_supplierinfo.xml
- demo/account_invoice.xml

[Ref](https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#file-naming)

2016-11-14 13:11 UTC, legalsylvain commented on account_invoice_product_supplier_price_update/account_invoice.py
> +            for seller in line.product_id.seller_ids:
something like that should more rapid:

    for seller in line.product_id.seller_ids.filtered(lambda seller: seller.name== supplier):

2016-11-14 13:11 UTC, legalsylvain commented on account_invoice_product_supplier_price_update/account_invoice.py
> +                    current_price_unit = [pricelist.price for pricelist in
Not a clear idea here, but I think we should think this algorithm as overloadable.

I think to [product_supplierinfo_discount](https://github.com/OCA/purchase-workflow/tree/10.0/product_supplierinfo_discount)

2016-11-25 10:30 UTC, legalsylvain commented
Hi @chafique-delli,
I took a deeply look on your PR. Some remarks :
* This module should be renamed better in account_invoice_supplierinfo_update because it's not only the price that is updated. (min_qty should be too)
* I still think that it should not depend on variant settings because it adds an unncessary dependency. It should be managed by glue module. The module you're sharing is very generic and is a must have feature, and supplierinfo for variant is specific. The current design will avoid some guys to install this module, or to have to disable manually some undesired features.
* This module doesn't work in all situation. Specially if there are some supplierinfo defined. (min_qty is not managed correctly).

I'm working on a PR on your PR, refactoring your PR. 

Thanks.

2016-11-26 15:16 UTC, legalsylvain commented
hi all, 

FYI

If you're interested by this module, a pending refactoring is available here. 
https://github.com/akretion/account-invoicing/pull/3

2016-12-13 17:01 UTC, legalsylvain approved these changes

2016-12-13 17:08 UTC, moylop260 commented on oca_dependencies.txt
> +product-variant
Where are required these repositories?

2016-12-13 17:08 UTC, legalsylvain commented
Hi. 
I just rebased this PR, after the last merge. 
@chafique-delli, could you squach your commits ? (I can make it if you want).
@sebastienbeau, @all could you review this PR updated ?

Thanks !

2016-12-13 17:10 UTC, chafique-delli commented
@legalsylvain , I want you to do it.Thank you.

2016-12-13 17:11 UTC, legalsylvain commented on oca_dependencies.txt
> +product-variant
Thanks for pointing this unused dependencies. I just fixed it.

2016-12-13 17:31 UTC, legalsylvain commented
Note : Travis is red because upstream 8.0 branch is red.

2016-12-16 16:14 UTC, sebastienbeau approved these changes

2016-12-16 16:14 UTC, sebastienbeau commented
Great work @legalsylvain @chafique-delli  ! Thx

2016-12-16 16:20 UTC, legalsylvain commented
This PR has been strongly refactored and is now validated by 2 people. ( @sebastienbeau and me), but as I wrote a lot of the refactored code, I'd prefer to have an full external :+1: 

@eLBati , @pedrobaeza , @elicoidal , @moylop260 : is someone interested to finish to review that PR that began to review ?

kind regards.

2016-12-16 16:54 UTC, moylop260 approved these changes
👍 
Thanks!

Just small comments non-blocking

2016-12-16 16:54 UTC, moylop260 commented on account_invoice_supplierinfo_update/models/account_invoice_line.py
> +        else:
If you have a `if-return` then the `else` is not needed

2016-12-16 16:54 UTC, moylop260 commented on account_invoice_supplierinfo_update/models/account_invoice_line.py
> +        supplierinfos = (self.product_id.seller_ids.filtered(
Unnecessary parents `(`

2016-12-16 16:54 UTC, moylop260 commented on account_invoice_supplierinfo_update/wizard/wizard_update_invoice_supplierinfo_line.py
> +        for line in self:
In order to reduce cyclomatic complexity (and quantity of tests to cover the code) you could remove `if-else` sentence using filtered and global write:
```python
self.write({'price_variation': False})
for line in self.filtered('current_price'):
     line.price_variation = 100 * (line.new_price - line.current_price) / line.current_price
```

2016-12-16 16:54 UTC, moylop260 commented on account_invoice_supplierinfo_update_discount/models/account_invoice_line.py
> +        res['current_discount'] = partnerinfo and partnerinfo.discount or False
new api supports BrowseNull.value <- `False`
Use: `res['current_discount'] = partnerinfo.discount`

2016-12-16 16:54 UTC, moylop260 commented on account_invoice_supplierinfo_update_variant/wizard/wizard_update_invoice_supplierinfo_line.py
> +                'product_id': self.product_id.id,
https://github.com/OCA/account-invoicing/blob/d0987a68bfc9c86a59e811c6262327d71cbafcb1/account_invoice_supplierinfo_update/wizard/wizard_update_invoice_supplierinfo_line.py#L62-L69

The original method have the same values but changing just `product_id`:
```python
    @api.multi
    def _prepare_supplierinfo(self):
        self.ensure_one()
        return {
            'product_tmpl_id': self.product_id.product_tmpl_id.id,
            'name': self.wizard_id.invoice_id.supplier_partner_id.id,
            'min_qty': 0.0,
            'delay': 1,
        }
```

What about use result from `super` and change to custom values required in pro of easiest inheriting?

`res = supers(...); res.update({...}); res.pop()`

(I don't know maybe is not possible)

2016-12-19 12:08 UTC, legalsylvain commented on account_invoice_supplierinfo_update_discount/models/account_invoice_line.py
> +        res['current_discount'] = partnerinfo and partnerinfo.discount or False
Your proposal doesn't work.

![bool_error](https://cloud.githubusercontent.com/assets/3407482/21312356/d2d85164-c5eb-11e6-83d6-24ce0cc178ab.png)

But the following line does work.

        res['current_discount'] = partnerinfo and partnerinfo.discount

2016-12-19 12:10 UTC, legalsylvain commented
@moylop260 : @chafique-delli and me updated our PR, according your last remarks.
Is it now all ok for you ? 

kind regards.

2017-01-03 10:48 UTC, legalsylvain commented
Ping @moylop260 !

(And happy New year !)

2017-01-12 15:26 UTC, legalsylvain commented
Previous review was OK. 3 :+1:. merging.

2017-01-12 15:26 UTC, merged