[FIX] 14.0 account_invoice_fixed_discount: fixing precompute tax line…
OCA/account-invoicing pull request #1586
Opened 2023-10-24 14:37 UTC by jumeldi74

…s fixing in function _recompute_tax_lines when retrive from sale order

2023-10-25 06:43 UTC, hitrosol commented
LGTM, the test is also green...

maybe you are interested on this @flotho @Saran440

2023-10-25 06:44 UTC, hitrosol approved these changes

2023-12-05 13:08 UTC, damdam-s approved these changes
works like a charm. thanks

2024-09-11 16:17 UTC, petrus-v commented
Dear @OCA/accounting-maintainers,

This receive approved label, do you mind to merge it?

Thanks a lot for your time.

2025-07-07 10:29 UTC, sergiocorato requested changes
Sorry but I don't understand the logic of this change, why use line_ids from an account.move?

What bug does this PR fix?

Tests are obviously green as the lines are the same plus the created lines to manage VAT and partner's debit/credit, which do not have the fixed discount as they are not visible on the main page of the invoice.

2025-12-21 12:23 UTC, closed without merging