9.0 [ADD] account_invoice_check_total
OCA/account-invoicing pull request #162
Opened 2016-07-12 09:49 UTC by ThomasBinsfeld

2016-07-12 09:49 UTC, ThomasBinsfeld commented
@sbidoul

2016-07-12 09:52 UTC, sbidoul commented on account_invoice_check_total/README.rst
> +<https://github.com/OCA/{project_repo}/issues>`_. In case of trouble, please
replace {project_repo}

2016-07-12 09:54 UTC, sbidoul commented on account_invoice_check_total/README.rst
> +
Add description such as:

Add a Verification Total field on vendor bills. The user enters the taxes included invoice total as printed on the vendor bill, then enters the invoice lines and taxes. The system then checks the total computed by Odoo is the same as the verification total.

2016-07-12 09:56 UTC, sbidoul commented on account_invoice_check_total/models/account_invoice.py
> +        default=0.0)
no default is needed I think (not tested yet)

2016-07-12 09:56 UTC, sbidoul commented on account_invoice_check_total/models/account_invoice.py
> +                raise UserError(_(
Better to use float_compare?

2016-07-12 13:18 UTC, sbidoul commented
@ThomasBinsfeld runbot is red because existing tests do set the check_total field when creating invoices.

Perhaps we should make check_total required on the supplier invoice/refund form and have the check trigger only if check_total is set.

What do you think?

2016-07-13 10:00 UTC, sbidoul commented
@ThomasBinsfeld it seems this is not finished, you need to
* declare the group like this https://github.com/odoo/odoo/blob/965024902db880af005a9688a277b28e076a4a7e/addons/account/security/account_security.xml#L29
* link the field to the group in the view

2016-07-15 07:39 UTC, sbidoul commented on account_invoice_check_total/security/account_invoice_security.xml
> +        <field name="name">Check Total on supplier bills</field>
Check Total on Vendor Bills

2016-07-15 07:40 UTC, sbidoul commented
@ThomasBinsfeld one last small remark. It now works fine.

:+1: (code review and functional test on runbot)

2016-09-05 07:45 UTC, adrienpeiffer commented
@ThomasBinsfeld I just add ```group_supplier_inv_check_total``` on ```account.config.settings```. So, it's now possible to add this group for all users in one click.

2016-09-30 13:32 UTC, atchuthan approved these changes
few minor corrections

Runbot test :+1:

2016-09-30 13:32 UTC, atchuthan commented on account_invoice_check_total/README.rst
> +
Add runbot link in Usage section
Use template from maintainers repo (https://raw.githubusercontent.com/OCA/maintainer-tools/master/template/module/README.rst)

2016-09-30 13:32 UTC, atchuthan commented on account_invoice_check_total/__openerp__.py
> +    'demo': [
Remove empty keys

2016-09-30 13:32 UTC, atchuthan commented on account_invoice_check_total/security/account_invoice_security.xml
> +<openerp>
use odoo instead of openerp for 9.0

2016-09-30 13:32 UTC, atchuthan commented on account_invoice_check_total/security/account_invoice_security.xml
> +<data noupdate="0">
make it as noupdate="1" or remove the tag itself

2016-09-30 13:32 UTC, atchuthan commented on account_invoice_check_total/views/account_config_settings.xml
> +<data>
replace openerp and data with odoo xml tag

2016-10-11 07:07 UTC, Cedric-Pigeon commented
:+1: code review

2016-10-11 07:19 UTC, pedrobaeza requested changes

2016-10-11 07:19 UTC, pedrobaeza commented on account_invoice_check_total/models/account_invoice.py
> +            gr = 'account_invoice_check_total.group_supplier_inv_check_total'
You can import the group from the other file to have only one reference

2016-10-11 07:19 UTC, pedrobaeza commented on account_invoice_check_total/models/account_invoice.py
> +        vals = super(AccountInvoice, self)._prepare_refund(invoice,
Use this for shorten the number of lines:
```
vals = super(AccountInvoice, self)._prepare_refund(
    invoice, date_invoice, date, description, journal_id)
```

2016-10-11 07:19 UTC, pedrobaeza commented on account_invoice_check_total/models/account_invoice.py
> +        if invoice and invoice.type in ['in_invoice', 'in_refund']:
No need to check previously `if invoice`. Only second condition is needed.

2016-10-11 07:19 UTC, pedrobaeza commented on account_invoice_check_total/static/description/icon.svg
> +<?xml version="1.0" encoding="UTF-8" standalone="no"?>
Put the PNG icon, not the SVG (unless it's an specific one)

2016-10-11 07:19 UTC, pedrobaeza commented on account_invoice_check_total/tests/test_account_invoice.py
> +        group_id = 'account_invoice_check_total.group_supplier_inv_check_total'
Import the group variable

2016-10-11 08:03 UTC, pedrobaeza commented
Please attend last comments and squash all the commits together by author, and I'll merge

2016-10-11 08:40 UTC, pedrobaeza requested changes

2016-10-11 08:40 UTC, pedrobaeza commented on account_invoice_check_total/tests/test_account_invoice.py
> +from openerp.addons.account_invoice_check_total.models.account_invoice\
Use `from ..models.account_invoice import GROUP_AICT`

2016-10-11 08:40 UTC, pedrobaeza commented on account_invoice_check_total/models/account_config_settings.py
> +GROUP_XML_ID = 'account_invoice_check_total.group_supplier_inv_check_total'
Import here also the group

2016-10-11 08:42 UTC, pedrobaeza commented
Please remember to squash commits

2016-10-11 08:51 UTC, ThomasBinsfeld commented
@pedrobaeza Thanks for the review. I squashed cosmetic commits to preserve a meaningful history.

2016-10-11 09:20 UTC, pedrobaeza commented
Please use relative import as requested, or the linter fails.

2016-10-11 09:21 UTC, pedrobaeza commented
I see still a lot of irrelevant commits at the beginning. Please squash them.

2016-10-11 13:25 UTC, adrienpeiffer commented
@pedrobaeza this one is now ok for you ?

2016-10-11 13:38 UTC, pedrobaeza commented
Yeah, this is better, thanks.

2016-10-11 13:38 UTC, merged