[17.0][MIG] account_invoice_fiscal_position_update: Migration to 17.0
OCA/account-invoicing pull request #1630
Opened 2023-12-20 07:52 UTC by moitabenfdz

2023-12-20 08:58 UTC, sbidoul commented
/ocabot migration account_invoice_fiscal_position_update

2024-06-17 07:45 UTC, MarwanBHL approved these changes

2024-07-01 13:22 UTC, rov-adhoc approved these changes

2024-07-11 13:03 UTC, rov-adhoc commented
@moitabenfdz Hi! Do you know why runboat is still pending?
Thanks

2024-07-11 13:14 UTC, sbidoul commented
> Hi! Do you know why runboat is still pending? Thanks

@rov-adhoc the last commit to this PR is very old, so the runboat build has likely been evicted to make room for others.

2024-07-24 11:29 UTC, FernandoRomera approved these changes
LGTM

2024-10-07 16:24 UTC, rov-adhoc commented
@moitabenfdz Hey could you please rebase this pr?

Regards

2024-11-07 09:27 UTC, miguel-S73 commented
functional review OK

2024-11-07 09:28 UTC, miguel-S73 approved these changes

2024-12-22 10:30 UTC, Jortolsa-S73 approved these changes
Functional review

2024-12-23 13:49 UTC, cav-adhoc commented
@moitabenfdz Hi! could you rebase this PR? runboat is in pending. Thanks!!

2024-12-23 23:17 UTC, moitabenfdz commented
This module (account_invoice_fiscal_position_update) is messing up with the new tests in account_invoice_section_sale_order, added in v17.0.

2025-01-30 10:17 UTC, legalsylvain requested changes
Hi @moitabenfdz Thanks a lot for porting this module.

I Just tested on runboat.  The bug described in this issue looks to be still present. could you take a look ? Thanks ! 

https://github.com/OCA/account-invoicing/issues/1896

2025-02-11 08:53 UTC, juancarlosonate-tecnativa commented
We should add https://github.com/OCA/account-invoicing/pull/1678. Can you also review https://github.com/OCA/account-invoicing/issues/1896 ?

2025-02-17 15:01 UTC, StefanRijnhart commented
@juancarlosonate-tecnativa #1678 was solved independently in commit ' [FIX]account_invoice_fiscal_position_update: fix error when changing fiscal position with a line without product and description'.

@moitabenfdz you can solve #1896 by cherry-picking this commit that was just merged in 18.0: https://github.com/OCA/account-invoicing/commit/b0d75e25d9eea7e7643c7ec71c69e27f18833e18

2025-03-04 08:22 UTC, juancarlosonate-tecnativa commented
im going to start working on this due to the user's inactivity

2025-03-06 16:53 UTC, closed without merging