9.0 add account invoice company search and group by
OCA/account-invoicing pull request #165
Opened 2016-07-13 15:54 UTC by susport

This module extends the functionality of account to search
and group by to company.

2016-07-27 13:21 UTC, jjscarafia commented
:+1:  very usefull, filtering and grouping by company on invoices should be native

2018-03-30 12:19 UTC, feketemihai requested changes

2018-03-30 12:19 UTC, feketemihai commented on account_invoice_company_search/README.rst
> +Account Invioce Company Search
Invoice...not Invioce

2018-03-30 12:19 UTC, feketemihai commented on account_invoice_company_search/__openerp__.py
> +    "name": "Account Invioce Company Search",
The same, Invoice instead on Invioce

2018-03-30 12:19 UTC, feketemihai commented on account_invoice_company_search/__openerp__.py
> +    'demo': [],
remove empty tags

2018-03-30 12:19 UTC, feketemihai commented on account_invoice_company_search/README.rst
> +To configure this module, you need to:
You can remove this, just leave No Configuration Needed..

2018-03-30 12:19 UTC, feketemihai commented on account_invoice_company_search/README.rst
> +The user has to be Multi company
The user needs to be in Multi Company group

2022-01-16 12:12 UTC, closed without merging