[MIG] [17.0] account_invoice_blocking migration to 17.0
OCA/account-invoicing pull request #1682
Opened 2024-03-12 15:21 UTC by luisDIXMIT

Standard migration

@etobella

2024-03-12 16:22 UTC, etobella approved these changes
Tested on runboat

LGTM

/ocabot migration account_invoice_blocking

2024-07-25 10:58 UTC, traitrantrobz requested changes
LGTM 👍

2024-07-25 10:59 UTC, traitrantrobz approved these changes
LGTM 👍

2024-07-25 12:19 UTC, etobella commented
/ocabot merge nobump

2024-07-25 12:24 UTC, merged