[17.0][MIG] account_global_discount: Migration to 17.0
OCA/account-invoicing pull request #1687
Opened 2024-03-18 09:23 UTC by miguel-S73

Standard migration to 17.0

Depends:
- [x] https://github.com/OCA/server-backend/pull/275

2024-06-17 15:18 UTC, pedrobaeza commented
/ocabot migration account_global_discount

2024-08-14 16:17 UTC, miguel-S73 commented
@pedrobaeza I apply same change that https://github.com/OCA/server-backend/pull/275#issuecomment-2289129850

2024-08-14 16:18 UTC, pedrobaeza commented
OK, some reviewers should validate this.

2024-11-06 14:40 UTC, miguel-S73 commented
@pedrobaeza all check are green.
We've thoroughly tested this module with multiple clients, and it performs reliably.

2024-11-06 14:58 UTC, pedrobaeza commented
Great. Now some reviewers are needed. We don't need this module for now.

2024-11-07 09:38 UTC, miguel-S73 commented
@etobella  @gurneyalex @grindtildeath  
Could one of you please review my changes?

We've thoroughly tested this module with multiple clients, and it performs reliably.

2024-12-02 07:54 UTC, Abimael1321 commented
Functionally reviewed. LGTM!

2024-12-02 07:55 UTC, Abimael1321 approved these changes

2024-12-12 08:53 UTC, miguel-S73 commented
I’d like to thank @Abimael1321  for testing this PR and confirming that it works as expected. 
With this validation, I believe the PR is ready to be merged.
 @pedrobaeza, Please let me know if there’s anything else needed. Thanks!

2024-12-12 09:07 UTC, pedrobaeza commented
2 reviewers are needed, and one coming from a PSC: https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#review

2024-12-24 12:03 UTC, AinohaBH commented
Functional: LGTM!

2025-01-07 19:09 UTC, dalonsod requested changes
See comments. Most of them look for commit noise reduction, and it seems that there are two errors in views.

2025-01-07 19:09 UTC, dalonsod commented on account_global_discount/models/account_move.py
> +            lambda line: line.display_type not in ["line_section", "line_note"]
This change should be removed, as unnecessary IMO (in this commit should only be added changes that are required, not cosmetic ones that make more difficult search for required changes related to commit goal according its description)

2025-01-07 19:09 UTC, dalonsod commented on account_global_discount/models/account_move.py
> +                    "name": "{} - {}".format(
The same as above

2025-01-07 19:09 UTC, dalonsod commented on account_global_discount/models/account_move.py
> +                    discounts |= discount
For company filtering `filtered` expressions, as old code does, could be used instead another `for` statement here

2025-01-07 19:09 UTC, dalonsod commented on account_global_discount/models/account_move.py
> +    # is properly filled Provided for compatibility in stable branch
This is strange, shouldn't be placed this change in previous commit, if it was a `pre-commit` execution consequence?

2025-01-07 19:09 UTC, dalonsod commented on account_global_discount/models/account_move.py
> +        ),
The same as above

2025-01-07 19:09 UTC, dalonsod commented on account_global_discount/models/global_discount.py
> +            "[('account_type', 'not in', ['asset_receivable', 'liability_payable'])]"
The same as above

2025-01-07 19:09 UTC, dalonsod commented on account_global_discount/tests/test_global_discount.py
> +            )
Unneeded change IMO, as explained above for a similar case

2025-01-07 19:09 UTC, dalonsod commented on account_global_discount/tests/test_global_discount.py
> +            lambda line: line.tax_line_id and not line.invoice_global_discount_id
The same as above

2025-01-07 19:09 UTC, dalonsod commented on account_global_discount/tests/test_global_discount.py
> +            )
The same as above

2025-01-07 19:09 UTC, dalonsod commented on account_global_discount/tests/test_global_discount.py
> +            lambda line: line.tax_line_id and not line.invoice_global_discount_id
The same as above

2025-01-07 19:09 UTC, dalonsod commented on account_global_discount/views/account_invoice_views.xml
> +                    invisible="global_discount_ids"
Is this right? The equivalent expression should be the opposite one, if I'm not wrong

2025-01-07 19:09 UTC, dalonsod commented on account_global_discount/views/account_invoice_views.xml
> +                    invisible="global_discount_ids_readonly"
The same as above

2025-01-08 08:52 UTC, AinohaBH approved these changes

2025-01-08 11:30 UTC, miguel-S73 commented on account_global_discount/models/account_move.py
> +            lambda line: line.display_type not in ["line_section", "line_note"]
Thank you for your review. I made this change because a red flag was triggered in the pre-commit test.

2025-01-08 11:30 UTC, miguel-S73 commented on account_global_discount/models/account_move.py
> +                    discounts |= discount
In the internal process of the "filtered" function, a "browse" is performed. In my opinion, this approach is more efficient than using the "filtered" function itself.

2025-01-08 11:31 UTC, miguel-S73 commented on account_global_discount/views/account_invoice_views.xml
> +                    invisible="global_discount_ids"
You’re absolutely right, thank you for pointing this out. I’ve fixed it now

2025-01-08 11:34 UTC, miguel-S73 commented
The remaining test failures are caused by another module, but there’s an active PR that addresses this issue.
- [ ] https://github.com/OCA/account-invoicing/pull/1871

2025-01-30 15:36 UTC, dalonsod requested changes
See comment, and there are some other `tree` view fields with `invisible="1"` that should be updated as well, if I'm not wrong

2025-01-30 15:36 UTC, dalonsod commented on account_global_discount/views/account_invoice_views.xml
> +                <field name="global_discount_item" invisible="1" />
These columns are actually shown:
```suggestion
                <field name="invoice_global_discount_id" column_invisible="1" />
                <field name="global_discount_item" column_invisible="1" />
```

2025-02-03 09:01 UTC, miguel-S73 commented on account_global_discount/views/account_invoice_views.xml
> +                <field name="global_discount_item" invisible="1" />
@dalonsod Thank you! I have fixed this.

2025-02-03 17:10 UTC, dalonsod requested changes
There are more `invisible` that should be moved to `column_invisible`, please check.

2025-02-03 17:10 UTC, dalonsod commented on account_global_discount/views/account_invoice_views.xml
> +                        <field name="discount" invisible="1" />
These fields should be applied with `column_invisible` as well

![imagen](https://github.com/user-attachments/assets/3b89d769-5cce-46f7-972a-72078c9f4ad9)

2025-02-03 17:10 UTC, dalonsod commented on account_global_discount/views/account_invoice_views.xml
> +                        <field name="discount" invisible="1" />
The same as above

2025-02-04 07:37 UTC, miguel-S73 commented on account_global_discount/views/account_invoice_views.xml
> +                        <field name="discount" invisible="1" />
@dalonsod You're absolutely right. Thanks for the correction. I've already fixed it.😊

2025-02-04 08:33 UTC, dalonsod commented on account_global_discount/views/account_invoice_views.xml
> +                        <field name="company_id" invisible="1" />
Still missing this?

2025-02-04 10:11 UTC, miguel-S73 commented on account_global_discount/views/account_invoice_views.xml
> +                        <field name="company_id" invisible="1" />
@dalonsod Yes, sorry, I overlooked it. Thanks again!

2025-02-04 10:54 UTC, dalonsod approved these changes
:+1: 

@AaronHForgeFlow is this PR ready to be merged? Thanks!

2025-02-04 11:43 UTC, miguel-S73 commented
Hi @pedrobaeza , this PR has received two approvals. Would it be possible to merge the changes?

2025-02-04 11:45 UTC, pedrobaeza commented
OK, let's go

/ocabot merge nobump

2025-02-04 11:53 UTC, merged