[16.0][IMP] partner_invoicing_mode_at_shipping: Extract _invoicing_at_shipping_validation function and add option auto validate invoice on partner
OCA/account-invoicing pull request #1695
Opened 2024-03-28 08:21 UTC by tuantrantg

Depends on:
* https://github.com/OCA/account-invoicing/pull/1628

2024-03-29 10:54 UTC, jbaudoux requested changes

2024-03-29 10:54 UTC, jbaudoux commented on partner_invoicing_mode_at_shipping/models/res_partner.py
> +    )
Do not add this. There is already that option
* invoicing mode at shipping: generate & validate invoice
* one_invoice_per_shipping: generate invoice & choose another option in invoicing mode if you want auto validation

2024-03-29 10:59 UTC, jbaudoux commented
This should be a PR on https://github.com/OCA/account-invoicing/pull/1628 unless @rousseldenis you rebase and merge your PR, then you can rebase this one...

2024-04-01 04:10 UTC, tuantrantg commented on partner_invoicing_mode_at_shipping/models/res_partner.py
> +    )
> one_invoice_per_shipping: generate invoice & choose another option in invoicing mode if you want auto validation
hi @jbaudoux could you please explain `another option in invoicing mode`, I don't get this point

2024-04-02 11:17 UTC, jbaudoux commented on partner_invoicing_mode_at_shipping/models/res_partner.py
> +    )
The method `_invoicing_at_shipping_validation` https://github.com/OCA/account-invoicing/pull/1695/files#diff-9805ceb19bf3584cef2fb4a911f57df11606716d8af657ebe54680627f90f2dfR25 currently implements [1].
We need to add there a condition in case of COD [2] to validated only if the COD payment term is configure so. So if COD, we rely only on COD config, otherwise we call super. This is because we use this module from COD to make the invoices. So we still need to rely only on COD config when called from there.

2024-04-03 08:43 UTC, tuantrantg commented
Hi @jbaudoux https://github.com/acsone/account-invoicing/pull/4 is created to follow this PR. I will close this one

2024-04-03 08:43 UTC, closed without merging