[17.0][MIG] partner_invoicing_mode: Migration to 17.0
OCA/account-invoicing pull request #1699
Opened 2024-04-08 19:54 UTC by NICO-SOLUTIONS

standard migration

2024-07-29 05:06 UTC, traitrantrobz requested changes

2024-07-29 05:06 UTC, traitrantrobz commented on partner_invoicing_mode/readme/DESCRIPTION.md
> +tab of the partner with a default value (Odoo standard invoicing mode).
I think this needs to be fixed. In Odoo version 17.0, the tab name 'Accounting' has been changed to 'Invoicing'.

2024-07-29 10:05 UTC, NICO-SOLUTIONS commented on partner_invoicing_mode/readme/DESCRIPTION.md
> +tab of the partner with a default value (Odoo standard invoicing mode).
adjusted

2024-07-30 08:41 UTC, traitrantrobz requested changes
@NICO-SOLUTIONS I think you should double-check against this migration. You can check at #1515 and #1295.

2024-07-30 08:49 UTC, traitrantrobz commented
![Ảnh chụp Màn hình 2024-07-30 lúc 15 48 10](https://github.com/user-attachments/assets/1cb9f8fe-7753-4aec-b481-75a3f1a4758a)

2024-08-06 03:50 UTC, traitrantrobz requested changes

2024-08-06 03:50 UTC, traitrantrobz commented on partner_invoicing_mode/views/res_config_settings.xml
> +                                <label
Please double-check position of `invoicing_mode_standard_last_execution `.
![Ảnh chụp Màn hình 2024-08-06 lúc 10 48 50](https://github.com/user-attachments/assets/ba7384d1-82f2-4922-acac-53b791006ca0)

2024-08-14 02:46 UTC, traitrantrobz approved these changes
LGTM 👍

2024-09-30 14:54 UTC, gurneyalex commented
/ocabot migration partner_invoicing_mode

2024-09-30 14:56 UTC, gurneyalex approved these changes

2024-09-30 14:57 UTC, gurneyalex commented
/ocabot merge nobump

2024-09-30 15:03 UTC, merged