[17.0][MIG] stock_picking_return_refund_option
OCA/account-invoicing pull request #1709
Opened 2024-04-18 08:26 UTC by mariobinhex

Standard migration with changes in fields views and test

2024-04-18 09:10 UTC, pedrobaeza commented
/ocabot migration stock_picking_return_refund_option

2024-05-02 16:50 UTC, christian-ramos-tecnativa requested changes

2024-05-02 16:50 UTC, Christian-RB commented on stock_picking_return_refund_option/views/stock_picking_view.xml
> +                    invisible="is_return == False"
I think for those cases is better to just use `not is_return`

2024-05-02 16:50 UTC, Christian-RB commented on stock_picking_return_refund_option/views/stock_picking_view.xml
> +                <field name="to_refund" column_invisible="parent.is_return == False" />
Same here

2024-05-06 07:20 UTC, MarioLM-23 commented on stock_picking_return_refund_option/views/stock_picking_view.xml
> +                <field name="to_refund" column_invisible="parent.is_return == False" />
Done

2025-05-12 12:02 UTC, david-banon-tecnativa approved these changes
Looks good to me

2025-05-12 14:47 UTC, pedrobaeza commented
@Christian-RB can you recheck your review? And maybe rebase for a final runboat test.

2025-05-12 15:33 UTC, christian-ramos-tecnativa commented
@pedrobaeza I don't have access to that repository, we can test it locally or I can create a new PR with the rebase and close this one

2025-05-12 15:35 UTC, pedrobaeza approved these changes
OK, let's merge and test once merged, and if any problem, we can put extra PRs.

/ocabot merge nobump

2025-05-12 15:45 UTC, merged