[17.0][MIG] sale_timesheet_invoice_description
OCA/account-invoicing pull request #1713
Opened 2024-04-24 13:44 UTC by mariobinhex

Standard migration with changes of old references

2024-04-28 07:03 UTC, bosd commented
Is it me or is there more going on in your first commit then just isort,prettier, black and pre-commit?

2024-04-28 07:37 UTC, bosd reviewed
Some minor improvements

2024-04-28 07:37 UTC, bosd commented on sale_timesheet_invoice_description/__manifest__.py
> +    "name": "Timesheet details invoice",
```suggestion
    "name": "Timesheet details invoice description",
```

2024-04-28 07:37 UTC, bosd commented on sale_timesheet_invoice_description/readme/USAGE.md
> +6.  Go to the Sale Order and create its invoice (clic on 'Create
```suggestion
6.  Go to the Sale Order and create its invoice (click on 'Create
```

2024-04-28 07:37 UTC, bosd commented on sale_timesheet_invoice_description/readme/USAGE.md
> +3.  Go to 'Other Info' tab (wihthin the same Sale Order) and:
```suggestion
3.  Go to 'Other Info' tab (within the same Sale Order) and:
```

2024-04-28 07:37 UTC, bosd commented on sale_timesheet_invoice_description/tests/test_sale_timesheet_description.py
> +from odoo.tests import common
```suggestion
from odoo.tests import common
from odoo.addons.base.tests.common import DISABLED_MAIL_CONTEXT
```

2024-04-28 07:37 UTC, bosd commented on sale_timesheet_invoice_description/tests/test_sale_timesheet_description.py
> +        # Make sure user is in English
```suggestion
cls.env = cls.env(context=dict(cls.env.context, **DISABLED_MAIL_CONTEXT))
        # Make sure user is in English
```

2024-04-29 08:27 UTC, MarioLM-23 commented
> Is it me or is there more going on in your first commit then just isort,prettier, black and pre-commit?

Yes sorry I changed the version in manifest, in the test file the super setUpClass and added contributors

2024-04-29 08:32 UTC, mariobinhex commented
@bosd 

I did the changes and improve the reference in xpath of configuration view, could you check it and let me know if I have done it correctly?
Thanks for the review!

2024-04-29 10:28 UTC, bosd commented
I've encountered an error, while testing on the runboat the default description feature.
Steps to reproduce.
On a SO set the Description to empty.
![image](https://github.com/OCA/account-invoicing/assets/11499387/25e9ff9f-cb36-40bf-a02f-787e6d323dca)

Then create an invoice:

Error occurs:
```
Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 1768, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/opt/odoo/odoo/http.py", line 1795, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/opt/odoo/odoo/http.py", line 1999, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/opt/odoo/odoo/addons/base/models/ir_http.py", line 222, in _dispatch
    result = endpoint(**request.params)
  File "/opt/odoo/odoo/http.py", line 725, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo/addons/web/controllers/dataset.py", line 28, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/dataset.py", line 20, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 468, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/addons/sale/wizard/sale_make_invoice_advance.py", line 180, in create_invoices
    invoices = self._create_invoices(self.sale_order_ids)
  File "/opt/odoo/addons/sale_timesheet/wizard/sale_make_invoice_advance.py", line 46, in _create_invoices
    return sale_orders.with_context(
  File "/mnt/data/odoo-addons-dir/sale_timesheet_invoice_description/models/sale.py", line 131, in _create_invoices
    desc_list = self._get_timesheet_description_list(ts_ids, desc_rule)
  File "/mnt/data/odoo-addons-dir/sale_timesheet_invoice_description/models/sale.py", line 41, in _get_timesheet_description_list
    details = self._get_timesheet_details(timesheet_id, desc_rule)
  File "/mnt/data/odoo-addons-dir/sale_timesheet_invoice_description/models/sale.py", line 29, in _get_timesheet_details
    if desc_rule[0] == "1":
TypeError: 'bool' object is not subscriptable

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (http://oca-account-invoicing-17-0-pr1713-fd442d552117.runboat.odoo-community.org/web/assets/0ab7b66/web.assets_web.min.js:2870:163)
    at XMLHttpRequest.<anonymous> (http://oca-account-invoicing-17-0-pr1713-fd442d552117.runboat.odoo-community.org/web/assets/0ab7b66/web.assets_web.min.js:2874:13)
```

I was expecting that the default method would be used insted. Which s configured in configuration--> settings.

2024-04-29 10:48 UTC, bosd commented
My last test actually leads me to reproduce another error.
After installation of this module. The default Timesheet description is on the empty value.
When creating a new invoice. This empty value is assigned. Leading to afforementioned error.

Proposal:
Remove the Empy value from the Invoice methods.
By default assign the value `[000] none` 

![image](https://github.com/OCA/account-invoicing/assets/11499387/1d0ae38e-ca07-4ec8-b855-b214402177ac)

2024-04-29 12:50 UTC, mariobinhex commented
@bosd Hello and thank you for checking those errors
The default value was already set to none, to solve the error of setting the description to empty I set the field in the views as required, with this it is solved?

2024-04-29 19:54 UTC, bosd commented
@mariobinhex Thanks for your patience and working on this bug.

I just discovered that this bug was already present in earlier versions.
So preferrebly the changes should be placed in a seperate commit for easy backport :hugs: 

The required flag works as inteded. It is no longer possible to assign the empty `False` value.
But, right after installation of this module. In configuration settings the value is still `False`.
We should set a default in python code. (just like on SO)
add
`default="000"`

at
https://github.com/OCA/account-invoicing/pull/1713/files#diff-3f0a25bc7aaab05ba3a84450130c78677a449cd2abbc4644e07786804d690a76R9-R13

If this module is installed in a DB with exsisting SO's. The error could still occur. (Because the value is False).
Or possibly when the SO is created via non UI.
For robustness we should adopt the code to allow for a `False` situation, I think changing this
https://github.com/OCA/account-invoicing/pull/1713/files#diff-26928443132d5ac74840f1c074ae427e24bdd060867bab3437730a4cc3e7c763R27-R35
to:
```
    def _get_timesheet_details(self, timesheet, desc_rule):
        details = []
        if desc_rule is False:
        return details
        if desc_rule[0] == "1":
            details.append(fields.Date.to_string(timesheet.date))
        if desc_rule[1] == "1":
            details.append(f"{timesheet.unit_amount} {timesheet.product_uom_id.name}")
        if desc_rule[2] == "1":
            details.append(timesheet.name)
        return details

```
Should do the trick.

2024-04-30 07:42 UTC, MarioLM-23 commented
@bosd Done! Please check my last commit when you can and tell me if any further changes are necessary

2024-04-30 11:04 UTC, bosd commented
@mariobinhex Thanks, please move the required flags to the last commit.
(For easy cherry picking, backports)

Please change the [commit message according to OCA guidelines](https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#commit-message)
`[IMP] sale_timesheet_invoice_description: Handle default description`
Or a better description 😄

2024-04-30 12:30 UTC, MarioLM-23 commented
@bosd Done, thanks for your patience looking for my mistakes and improving the code

2024-04-30 12:42 UTC, bosd approved these changes
LGTM ✨  Thanks for contributing

2024-05-01 08:05 UTC, Dranyel-Bosd approved these changes
LGTM :+1:  :sparkler:

2024-05-14 15:08 UTC, remi-filament approved these changes
LGTM thank you for your work @MarioLM-23

2024-05-14 15:10 UTC, pedrobaeza commented
Please squash last 2 commits into one, as both belongs to the migration itself.

2024-05-14 16:05 UTC, bosd commented
> Please squash last 2 commits into one, as both belongs to the migration itself.

I've actually requested to have the fix of the bug I've discovered to be in a seperate commit. 
(Bug was present in V15+, likely in 14 as well)
For easier cherry picking / backporting. (Which is now in the last commit)
@pedrobaeza Is that ok to you?

2024-05-14 16:13 UTC, pedrobaeza commented
That commit contains changes in the README, which doesn't seem correct.

2025-02-03 10:33 UTC, andreschenkels commented
@pedrobaeza @MarioLM-23 is it possible to resolve the questions so it can be merged? It's done but never merged.

2025-02-03 10:35 UTC, pedrobaeza commented on sale_timesheet_invoice_description/views/sale_view.xml
> +                <field name="timesheet_invoice_description" required="1" />
Why forcing this?

2025-02-17 07:47 UTC, victoralmau requested changes

2025-02-17 07:47 UTC, victoralmau commented on sale_timesheet_invoice_description/tests/test_sale_timesheet_description.py
> +        cls.env = cls.env(context=dict(cls.env.context, **DISABLED_MAIL_CONTEXT))
```suggestion
from odoo.addons.base.tests.common import BaseCommon


class TestSaleTimesheetDescription(BaseCommon):
    @classmethod
    def setUpClass(cls):
        super().setUpClass()
```

2025-04-16 16:09 UTC, victoralmau commented
Superseded by https://github.com/OCA/account-invoicing/pull/1985

2025-04-16 16:34 UTC, closed without merging