[17.0] [MIG] saleorder invoicing grouping criteria
OCA/account-invoicing pull request #1752
Opened 2024-07-02 15:23 UTC by RogerSans

2024-07-02 16:19 UTC, HaraldPanten commented
/ocabot migration sale_order_invoicing_grouping_criteria

2024-07-12 09:02 UTC, luis-ron approved these changes
Functional Review: LGTM 👍🏻

2024-07-12 12:34 UTC, Tisho99 requested changes
Please, review the README, i think that the strings of the menus and the buttons  have changed in v17

Here are 2 examples

![image](https://github.com/user-attachments/assets/3d59685e-ec71-44d0-b457-36463d20d965)

2024-07-12 12:34 UTC, Tisho99 commented on sale_order_invoicing_grouping_criteria/README.rst
> +1. Go to *Sales > Invoicing > Orders to Invoice*.
```suggestion
1. Go to *Sales > To Invoice > Orders to Invoice*.
```

2024-07-12 12:34 UTC, Tisho99 commented on sale_order_invoicing_grouping_criteria/README.rst
> +3. Click on *Action > Invoice Order*.
```suggestion
3. Click on *Action > Create Invoices*.
```

2024-07-12 12:42 UTC, Tisho99 commented on sale_order_invoicing_grouping_criteria/tests/test_sale_order_invoicing_group_criteria.py
> +    @classmethod
Are you sure this changes are needed? I think that if the requests library was nos used before we don't have to add this code

2024-07-12 12:49 UTC, Tisho99 commented on sale_order_invoicing_grouping_criteria/tests/test_sale_order_invoicing_group_criteria.py
> +    @classmethod
I refer to all changes done in tests

2024-07-15 08:13 UTC, RogerSans commented on sale_order_invoicing_grouping_criteria/README.rst
> +1. Go to *Sales > Invoicing > Orders to Invoice*.
Changed

2024-07-15 08:13 UTC, RogerSans commented on sale_order_invoicing_grouping_criteria/README.rst
> +3. Click on *Action > Invoice Order*.
Changed

2024-07-15 08:43 UTC, RogerSans commented on sale_order_invoicing_grouping_criteria/tests/test_sale_order_invoicing_group_criteria.py
> +    @classmethod
removed

2024-07-15 08:55 UTC, Tisho99 requested changes

2024-07-15 08:55 UTC, Tisho99 commented on sale_order_invoicing_grouping_criteria/tests/test_sale_order_invoicing_group_criteria.py
> +from odoo.tests import TransactionCase, requests
You also need to remove this

2024-07-15 08:55 UTC, Tisho99 commented on sale_order_invoicing_grouping_criteria/tests/test_sale_order_invoicing_group_criteria.py
> +        cls._super_send = requests.Session.send
You also need to remove this

2024-07-15 09:20 UTC, RogerSans commented on sale_order_invoicing_grouping_criteria/tests/test_sale_order_invoicing_group_criteria.py
> +        cls._super_send = requests.Session.send
Done

2024-07-15 09:20 UTC, RogerSans commented on sale_order_invoicing_grouping_criteria/tests/test_sale_order_invoicing_group_criteria.py
> +from odoo.tests import TransactionCase, requests
Done

2024-07-15 09:37 UTC, Tisho99 approved these changes
LGTM

2024-07-15 14:24 UTC, HaraldPanten reviewed
@RogerSans you forgot to add Sygel contributors. Didn't you?

2024-07-15 14:47 UTC, RogerSans commented
> @RogerSans you forgot to add Sygel contributors. Didn't you?

Yes, my mistake. Added.

2024-07-16 12:10 UTC, HaraldPanten commented
/ocabot merge nobump

2024-07-16 12:15 UTC, merged