[16.0][MIG] account_invoice_warn_message: Migration to 16.0
OCA/account-invoicing pull request #1783
Opened 2024-08-26 11:00 UTC by RogerSans

Standard Migration
T-6530

2024-08-26 13:32 UTC, Jaimermaccione approved these changes
@RogerSans LGMT!. The module has been tested on Runboat and works well. 

There's just a small visual detail that could be improved if it's not too costly to modify. The information icon is placed too close to the configured text in the client. I’ve compared versions, and in v17, it’s also close, but in v15, there's a space between the icon and the text, which gives a better visual appearance. Functionally, it’s perfect, so I’m giving it my approval, but that change would leave a better finish.

Test on V15:
![image](https://github.com/user-attachments/assets/5f1fd6aa-ad9b-4579-a878-73a646bc5635)
Test on v17:
![image](https://github.com/user-attachments/assets/ff5399ce-0e04-4f09-acd7-f05a297b62a8)

2024-08-26 13:50 UTC, ValentinVinagre commented
> @RogerSans LGMT!. The module has been tested on Runboat and works well.
> 
> There's just a small visual detail that could be improved if it's not too costly to modify. The information icon is placed too close to the configured text in the client. I’ve compared versions, and in v17, it’s also close, but in v15, there's a space between the icon and the text, which gives a better visual appearance. Functionally, it’s perfect, so I’m giving it my approval, but that change would leave a better finish.
> 
> Test on V15: ![image](https://private-user-images.githubusercontent.com/153611478/361449047-5f1fd6aa-ad9b-4579-a878-73a646bc5635.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2ODAzNjYsIm5iZiI6MTcyNDY4MDA2NiwicGF0aCI6Ii8xNTM2MTE0NzgvMzYxNDQ5MDQ3LTVmMWZkNmFhLWFkOWItNDU3OS1hODc4LTczYTY0NmJjNTYzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNlQxMzQ3NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOTFlZDljODFhYzg5NTA1NmFhOTVmNjhhZjA5ODZmNjNiNDE4ZTA5MjE2OWJhOWNkZDE0YzAwNzlmMDZkNzk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XS0x2nIpfyb_Qbsk93UzoRC0xYFHwXJEVQJnEaY7nCM) Test on v17: ![image](https://private-user-images.githubusercontent.com/153611478/361449254-ff5399ce-0e04-4f09-acd7-f05a297b62a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2ODAzNjYsIm5iZiI6MTcyNDY4MDA2NiwicGF0aCI6Ii8xNTM2MTE0NzgvMzYxNDQ5MjU0LWZmNTM5OWNlLTBlMDQtNGYwOS1hY2Q3LWYwNWEyOTdiNjJhOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNlQxMzQ3NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZmIwNDZmYmM1MGZkYzNiMWExMWM0NWYwZWFhMGM0MWFhYTMxNmFlMjlkNmZhMzQyZGE4NThiOWU3YjhmNzliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wqhs1hRaTyUeJfgSjDeLOxLV9ARvUD8i3Nsuq6KdS7w)

@RogerSans 
Could you, if it is not too expensive, make the change for both versions? I agree that it improves the display.

2024-08-26 17:24 UTC, rafaelbn commented
/ocabot migration account_invoice_warn_message

2024-08-27 06:09 UTC, RogerSans commented
Can you review the visual solution pls?
@ValentinVinagre 
@Jaimermaccione

2024-08-27 06:20 UTC, Jaimermaccione approved these changes
@RogerSans LGTM! Functional review on runboat!

2024-08-27 08:58 UTC, ValentinVinagre commented
Try to have the icon above the text and not at the bottom and make sure the full width is used in the display, since currently only half of the space is used.
![image](https://github.com/user-attachments/assets/6bfc4b40-c879-4b55-91c5-c2553a6de8cc)

2024-09-05 14:23 UTC, RogerSans commented
Changed to full use in the display warning.
![Selección_010](https://github.com/user-attachments/assets/d9d70e12-c9bd-4240-bdc4-b6041238fd2d)

2024-09-05 16:19 UTC, ValentinVinagre commented on account_invoice_warn_message/readme/CONTRIBUTORS.md
> +- Manuel Regidor \<<manuel.regidor@sygel.es>\>
Use this format please:

https://github.com/OCA/l10n-spain/blob/6c9a473b1607f52da7295fafaaae4eae70149f32/l10n_es_aeat_mod303/readme/CONTRIBUTORS.md?plain=1#L9-L11

2024-09-05 17:01 UTC, HaraldPanten requested changes
Some comments:

1. You're mixing pre-commit stuff and Migration changes in the same commit. You should separate them.
2. The tag in the migration commit [FWD] is not correct. You have to change it by [MIG]. The same for the PR title.

THX!

2024-09-06 08:42 UTC, RogerSans commented
@HaraldPanten 
Solved 
THX

2024-09-06 09:10 UTC, HaraldPanten approved these changes
LGTM.

My fault when I said my comments about the pre-commit, as it is a migration from V17 to V16 and there are no pre-commit changes.

2024-09-06 09:10 UTC, HaraldPanten commented
/ocabot merge nobump

2024-09-06 09:25 UTC, merged