[18.0][MIG] sale_order_invoicing_grouping_criteria migration to 18.0
OCA/account-invoicing pull request #1815
Opened 2024-10-17 11:15 UTC by BertVGroenendael

2024-10-17 11:29 UTC, pedrobaeza commented
/ocabot migration sale_order_invoicing_grouping_criteria

2025-02-05 19:16 UTC, carlos-lopez-tecnativa requested changes
Tested locally, working as expected.

Please squash administrative commits according to the guide:
https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests

TT54281
@Tecnativa

2025-02-05 19:16 UTC, carlos-lopez-tecnativa commented on sale_order_invoicing_grouping_criteria/views/res_config_settings_views.xml
> +                    <block>
Please update the view using the correct elements. In this case, this must be done during the migration to V17, but it is also applicable to V18. Please read the guide:
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0
![image](https://github.com/user-attachments/assets/e30b4ebf-9f74-4269-8446-c65844e319a3)

2025-02-12 14:06 UTC, carlos-lopez-tecnativa commented on sale_order_invoicing_grouping_criteria/views/res_config_settings_views.xml
> +                    <block>
ping @BertVGroenendael

2025-02-20 11:32 UTC, carlos-lopez-tecnativa commented on sale_order_invoicing_grouping_criteria/views/res_config_settings_views.xml
> +                    <block>
ping @BertVGroenendael

2025-02-25 07:22 UTC, pedrobaeza commented
Superseded by #1922

2025-02-25 07:22 UTC, closed without merging