[13.0][IMP] account_invoice_show_currency_line_rate: add journal item rate and consider journal item balance for credit amounts
OCA/account-invoicing pull request #1838
Opened 2024-11-11 09:25 UTC by JordiMForgeFlow

2024-11-11 09:59 UTC, JordiMForgeFlow commented
@victoralmau could you check these changes? :)

2024-11-11 10:13 UTC, AaronHForgeFlow commented
Is the new field because the currency rate in the lines can be different from the currency rate of the journal entries? is that because of manual editions of the amount currency?

2024-11-11 10:17 UTC, JordiMForgeFlow commented
@AaronHForgeFlow you can create misc entries with lines having different currency. Odoo already provides this field from >=V16

2024-11-11 10:37 UTC, AaronHForgeFlow approved these changes
Code review LGTM

2024-11-14 11:08 UTC, JoanSForgeFlow approved these changes
LGTM!

2025-01-22 15:32 UTC, victoralmau requested changes
I don't know exactly the specific use case that is solved, can you add a test to confirm it?

What is the real need to add the `currency_rate_amount` field all `account.move.line` records (You must set a migration script to create the column and set the values that corresponds).

2025-01-23 12:43 UTC, JordiMForgeFlow commented
@victoralmau the rate in the journal items is not stored.

The currency rate is actually added to journal items in V16 (https://github.com/odoo/odoo/blob/e614f082a95a249e4abc29ee7a7e3a3bcaedd9ea/addons/account/models/account_move_line.py#L115). It is useful for entries where different currencies may be involved.

2025-01-24 09:18 UTC, victoralmau commented
> @victoralmau the rate in the journal items is not stored.
> 
> The currency rate is actually added to journal items in V16 (https://github.com/odoo/odoo/blob/e614f082a95a249e4abc29ee7a7e3a3bcaedd9ea/addons/account/models/account_move_line.py#L115). It is useful for entries where different currencies may be involved.

OK sorry, I hadn't seen it. I think it would be interesting to add a TODO comment to indicate that this field and method should be removed in v16 because account already adds it with the `currency_rate` field.

2025-01-27 09:08 UTC, JordiMForgeFlow commented
@victoralmau now it should be ready :)

2025-01-27 09:13 UTC, victoralmau approved these changes

2025-01-27 09:33 UTC, AaronHForgeFlow commented
/ocabot merge minor

2025-01-27 09:46 UTC, merged