[MIG] [16.0] account_invoice_clearing
OCA/account-invoicing pull request #1858
Opened 2024-12-04 12:15 UTC by Shide

- Changing related account type fields and renamed those functions.
- Dropping Add button and Remove button because reset button does the same.
- Reworked a little bit the UI because groups works in a different way.
- Removed readonly fields related to analytic (just was info).
- Hide sequence column when someone starts to add amounts to clear (causes a crash).
- Fixed tests
- Make protected some functions that are not called via UI

MT-3067 @moduon @fcvalgar @rafaelbn @yajo @Gelojr please review if you want :)

2024-12-10 11:13 UTC, yajo approved these changes
Code review.

2024-12-11 23:38 UTC, rafaelbn approved these changes
Thank you! 👍🏼 

/ocabot merge patch

2024-12-16 11:26 UTC, Shide commented
@legalsylvain can you check failure of tests on your module when this module is merging? https://github.com/OCA/account-invoicing/actions/runs/12286819756/job/34287688237#step:8:189

2024-12-16 12:25 UTC, legalsylvain commented
@Shide which module ?

2024-12-16 12:34 UTC, Shide commented
> @Shide which module ?

https://github.com/OCA/account-invoicing/tree/16.0/account_invoice_pricelist

2024-12-16 12:39 UTC, legalsylvain commented
Sorry. I didn't implemented the "secondary currency" part (and never worked on multi currency). Better if another maintainer takes a look on that topic.

regards.

2024-12-17 16:05 UTC, Gelojr requested changes
I have discovered 2 errors:
- In a multi-company environment, the wizard seems to show invoices from the 2 companies.
- When sorting by due date, a traceback appears.
Video:  https://www.loom.com/share/506fdbdd16e54983989d6136ac40a2a6?sid=54162518-11de-450b-86ed-6abc9b4d87a1

2025-01-10 08:37 UTC, Gelojr approved these changes
LGTM Thanks @Shide 
https://www.loom.com/share/d23b4862e15249fea38a5dab55c5f26d?sid=ff8d8779-6983-4e4f-a66e-4ed88f036f7b

2025-01-10 09:37 UTC, rafaelbn commented
/ocabot merge patch

2025-01-10 09:53 UTC, merged