[MIG][18.0] Migration of account_invoice_merge from 16.0
OCA/account-invoicing pull request #1870
Opened 2024-12-31 09:37 UTC by acsonefho

Migration of `account_invoice_merge` from 16.0

2025-03-13 10:46 UTC, SamyBrahimi approved these changes

2025-04-07 15:09 UTC, matteonext commented
I created an invoice, saved it as a draft, and then duplicated it. When trying to merge, I don't see the 'Confirm' button, even though all the conditions in the warning are met. It works properly doing the same steps in v16.
![image](https://github.com/user-attachments/assets/a0b13de3-de4e-44bf-9a9c-feb676906525)

2025-05-22 05:15 UTC, rven commented on account_invoice_merge/models/account_move.py
> +            "payment_reference": "{invoice.payment_reference or ''}",
This is wrongly migrated
```suggestion
            "payment_reference": invoice.payment_reference or "",
```

2025-05-22 05:15 UTC, rven commented on account_invoice_merge/models/account_move.py
> +            "invoice_origin": f"{invoice.invoice_origin or ''}",
f-string has no use here
```suggestion
            "invoice_origin": invoice.invoice_origin or "",
```

2025-05-22 05:15 UTC, rven commented on account_invoice_merge/models/account_move.py
> +            "name": f"{invoice.name or ''}",
f-string has no use here
```suggestion
            "name": invoice.name or "",
```

2025-05-22 05:57 UTC, acsonefho commented
Thank you for your review @rven ! I just fix it :muscle:

2025-05-22 07:07 UTC, rven commented on account_invoice_merge/wizard/invoice_merge.py
> +from odoo import _, api, fields, models
```suggestion
from odoo import api, fields, models
```
Can be replaced by `self.env._`

2025-05-22 07:07 UTC, rven commented on account_invoice_merge/wizard/invoice_merge.py
> +        action = self.env["ir.actions.act_window"]._for_xml_id(f"account.{xid}")
Could maybe be replaced by `_get_records_action`

2025-05-22 07:11 UTC, acsonefho commented on account_invoice_merge/wizard/invoice_merge.py
> +from odoo import _, api, fields, models
Not mandatory. I'm letting this like that :pray:

2025-05-22 07:11 UTC, acsonefho commented on account_invoice_merge/wizard/invoice_merge.py
> +        action = self.env["ir.actions.act_window"]._for_xml_id(f"account.{xid}")
Not mandatory. I'm letting this like that :pray:

2025-05-22 07:20 UTC, rven approved these changes

2025-05-22 07:21 UTC, rven requested changes
Check the failing pipeline please!

2025-05-22 07:23 UTC, acsonefho commented
> Check the failing pipeline please!

Yes it's on my todo list. I can't reproduce right now so I have to take more time to investigate :/

2025-06-16 13:26 UTC, matteotognini requested changes

2025-06-16 13:26 UTC, matteotognini commented on account_invoice_merge/tests/test_account_invoice_merge.py
> +        cls.company2 = cls.env.company.search(
I tried it locally and these changes are needed to fix the tests:
```
cls.company_data2 = cls.setup_other_company()
cls.company2 = cls.company_data2['company']
```
I also opened a PR on your repo with these changes, if you prefer
Thanks

2025-07-23 03:50 UTC, P-H-Phuc requested changes

2025-07-23 03:50 UTC, P-H-Phuc commented on account_invoice_merge/wizard/invoice_merge_view.xml
> +                        invisible="not error_message"
This button should be visible when there is no `error_message`. So, change it to: `invisible="error_message"`

2025-07-25 10:29 UTC, tobiaszehntner commented on account_invoice_merge/wizard/invoice_merge_view.xml
> +                        invisible="not error_message"
Fixed. Thank you 🙌

2025-08-12 07:40 UTC, P-H-Phuc commented on account_invoice_merge/tests/test_account_invoice_merge.py
> +        cls.company2 = cls.env.company.search(
Hi @acsonefho , I’ve reviewed these changes and believe they should resolve the CI test failures. Could you apply them to your PR?

2025-08-12 07:55 UTC, acsonefho commented on account_invoice_merge/tests/test_account_invoice_merge.py
> +        cls.company2 = cls.env.company.search(
I already applied and test locally but it doesn't fix the issue. I just push it but it'll fail.
I didn't take time to investigate more but I'll.
Do not hesitate to take a look if you have time :pray: 
Thanks for the review and help :muscle:

2025-09-11 13:06 UTC, Alexis-SDK commented
Any news for this PR ?

2026-04-16 15:30 UTC, jusle approved these changes
LGTM

2026-04-16 15:31 UTC, jusle commented
According to my understanding, the failed tests are related to another module, `account_invoice_pricelist`.

2026-04-23 14:27 UTC, JuanJaraSandoval commented
Hi, any news on this PR? Any estimated release date?

2026-05-05 07:07 UTC, flotho commented
Hi @acsonefho , any chance to rebase to give a new chance to this PR to go to merge ?
Regards

2026-05-05 07:21 UTC, DorianMAG commented
Hi, can you rebase plz.
Can't acces to Runboat to make functional test.
Thx

2026-05-05 08:12 UTC, JulienMartinez approved these changes
Review and test of the Runboat 
LGTM

2026-05-05 08:53 UTC, DorianMAG approved these changes
Functional test.
LGTM.
Thx for this work

2026-05-05 09:22 UTC, JuanJaraSandoval commented
@acsonefho @flotho  Thank you all for bringing this request to life; I hope it will be closed soon on the main branch.

2026-05-05 09:27 UTC, acsonefho commented
@rousseldenis Can you merge this please? :pray:

2026-05-05 09:28 UTC, rousseldenis commented
> @rousseldenis Can you merge this please? 🙏

No superpower here

2026-05-05 09:29 UTC, rousseldenis commented
@OCA/accounting-maintainers

2026-05-12 07:00 UTC, JuanJaraSandoval commented
@acsonefho @rousseldenis Is it possible that some approval is missing for this pull request to be approved?

2026-06-08 06:51 UTC, sergiocorato approved these changes
/ocabot merge nobump

2026-06-08 07:09 UTC, merged