Add time sheet user name in invoice description
OCA/account-invoicing pull request #188
Opened 2016-10-04 15:18 UTC by EBII

in case of services the user who write time is not the client to invoice so it can read who made the job..

2016-10-05 13:09 UTC, pedrobaeza commented
Please squash your commits, and send the CLA according https://odoo-community.org/page/cla

2016-10-05 13:31 UTC, EBII commented
send the CLA according https://odoo-community.org/page/cla ... send it yesterday ;o) 
regards

2016-10-13 11:12 UTC, rousseldenis requested changes

2016-10-13 11:12 UTC, rousseldenis commented on sale_timesheet_invoice_description/tests/test_sale_timesheet_description.py
> +
@EBII Delete these comments or activate tests

2016-11-11 11:42 UTC, EBII commented
there is issue with this PR in case of module migration:
The choice get one more digits and all older settings became empty 
need to had 0 before in all value in base in case of upgrade.
maybe this year..

2017-04-06 13:59 UTC, mourad-ehm commented
Code review :+1:

2017-08-03 12:02 UTC, pedrobaeza commented
:-1: This is not valid while you:

* Uncomment tests and make them pass.
* Make migration script or don't change values.

2022-02-27 12:12 UTC, closed without merging