MIG 9.0 invoice_fiscal_position_update
OCA/account-invoicing pull request #196
Opened 2016-10-14 14:33 UTC by angelmoya

2016-10-15 12:06 UTC, pedrobaeza requested changes
You should include tests

2016-10-15 12:06 UTC, pedrobaeza commented on invoice_fiscal_position_update/models/account_invoice.py
> +    def fiscal_position_id_change(self):
Use standard nomenclature `onchange_fiscal_position_id`

2016-10-19 13:57 UTC, angelmoya commented
fix to use standard nomenclature and test added

2016-10-19 14:01 UTC, pedrobaeza commented on invoice_fiscal_position_update/models/account_invoice.py
>                      taxes = product.taxes_id
This is not filtered by company

2016-10-19 14:01 UTC, pedrobaeza commented on invoice_fiscal_position_update/models/account_invoice.py
>                      taxes = product.supplier_taxes_id
This is not filtered by company

2016-10-19 14:01 UTC, pedrobaeza commented on invoice_fiscal_position_update/models/account_invoice.py
>                      taxes = fp.map_tax(taxes)
This is not filtered by company

2016-10-19 14:41 UTC, angelmoya commented on invoice_fiscal_position_update/models/account_invoice.py
>                      taxes = fp.map_tax(taxes)
OK, fixed

2016-11-16 09:07 UTC, angelmoya commented
Code coverage decreased, but all code of this module is tested, I think it has been decreased from actual commit of branch 9.0, but it's not relevant

2016-11-16 14:39 UTC, pedrobaeza commented
Not really. You are not testing everything. It lacks the `else` parts. Look for example https://codecov.io/gh/OCA/account-invoicing/compare/916a44af4fa3c265c76ae54da282153cff44edf8...5d4952f6726fb3acd544776a4daadb066aa43a55#696E766F6963655F66697363616C5F706F736974696F6E5F7570646174652F6D6F64656C732F6163636F756E745F696E766F6963652E7079-47

You have 2 options:

* If it's a weird else condition, you can put `else:  # pragma: no cover` to avoid the coverage check.
* Create a special test for that condition if not.

2016-11-16 14:40 UTC, pedrobaeza commented on invoice_fiscal_position_update/README.rst
> +   :target: https://runbot.odoo-community.org/runbot/95/10.0
This should be 9.0

2017-01-31 04:10 UTC, sergio-teruel commented
cc @Tecnativa

2017-01-31 07:38 UTC, pedrobaeza commented
Superseeded by #223

2017-01-31 07:38 UTC, closed without merging