[9.0][ADD][account_invoice_refund_option] Create refund invoices directly
OCA/account-invoicing pull request #205
Opened 2016-11-07 12:42 UTC by Yajo

This addon lets you create a refund out of nothing.

Includes workaround for https://github.com/odoo/odoo/pull/14187

@Tecnativa

2016-11-07 14:59 UTC, pedrobaeza requested changes
Minor things + add Spanish translation instead of .empty file.

2016-11-07 14:59 UTC, pedrobaeza commented on account_invoice_refund_option/README.rst
> +an invoice to be a refund and to allow you to create refunds directly, linked
s/linked to nothing/without the need of refunding an existing normal invoice.

2016-11-07 14:59 UTC, pedrobaeza commented on account_invoice_refund_option/__openerp__.py
> +    "summary": "Allows you to create a refund linked to nothing",
`Allows you to create directly a refund without starting from an invoice`

2016-11-11 17:57 UTC, rafaelbn approved these changes
Tested in runbot

2016-11-11 18:40 UTC, pedrobaeza approved these changes

2016-11-11 18:42 UTC, merged