[10.0] Port account_invoice_rounding
OCA/account-invoicing pull request #212
Opened 2016-12-21 16:31 UTC by grindtildeath

2017-04-17 08:11 UTC, leemannd requested changes
Thanks for the port. Only nitpicking

2017-04-17 08:11 UTC, leemannd commented on account_invoice_rounding/models/account.py
>  #    along with this program.  If not, see <http://www.gnu.org/licenses/>.
Short header

2017-04-17 08:11 UTC, leemannd commented on account_invoice_rounding/models/company.py
>  #
Short headers

2017-04-17 08:11 UTC, leemannd commented on account_invoice_rounding/tests/test_invoice_rounding.py
> +import openerp.tests.common as test_common
s/openerp/odoo/

2017-06-14 09:31 UTC, leemannd approved these changes

2017-10-18 11:02 UTC, hurrinico commented
i've create [this](https://github.com/grindtildeath/account-invoicing/pull/3) in order to fix a bug using globally swedish round and fix the readme.rst.
To reproduce the bug:
Go to runbot.
set swedish round global.
create invoice add a product and set unit price 2,99 with tax 10%
try to add another line in order to trigger the onchange, you can see tax set as 0,31 and the total as 3,30
if you save tax goes to 0,01 and total to 3,00.
This PR fix it

2017-10-20 15:41 UTC, grindtildeath commented
@hurrinico Thanks for your PR.
I could reproduce the bug on runbot but not on my local instance because I used an `account.tax` having `price_included = True`.
Then I tried setting this flag to False, and could reproduce the bug you reported without your fix.
However, after pulling your branch the behaviour is still the same using `account.tax` without price_included :confused: 
As it's friday 5.30pm passed, I won't look more into it now, and will try to spend some time on it next week. :sweat_smile:

2017-10-23 15:43 UTC, grindtildeath commented
@hurrinico @leemannd @guewen 
PR fixed, can you please review ?

2017-10-23 15:58 UTC, hurrinico commented
there's a problem, travis is failing cause of api.one, but we need it in order to fix a bug

2017-10-24 07:37 UTC, grindtildeath commented
@hurrinico Actually flake8 check is failing because of this line https://github.com/OCA/account-invoicing/blob/10.0/account_payment_term_extension/models/account_payment_term.py#L70
So it has nothing to do with this PR.

2017-10-24 08:16 UTC, hurrinico commented
@grindtildeath maybe a rebase to OCA/10 will fix it.
I suggest also to squash commits by author, in order to have 2 commits here one mine one yours

2017-10-24 09:49 UTC, grindtildeath commented
@hurrinico We will need this https://github.com/OCA/account-invoicing/pull/324 to be merged before a rebase.
I will wait on it to squash commits at the same time.

2017-10-25 08:16 UTC, hurrinico commented
@grindtildeath great :+1: after the fix

2017-10-25 10:32 UTC, tafaRU commented
@grindtildeath, you could rebase on top considering that https://github.com/OCA/account-invoicing/pull/324 now is merged.
Thank you in advance.

2017-11-06 16:25 UTC, hurrinico commented
great work @grindtildeath thank  you for the fix :+1:

2017-12-14 17:23 UTC, grindtildeath commented
@hurrinico @tafaRU Could you please review so we can get this merged ?

2017-12-18 15:00 UTC, eLBati commented
@grindtildeath please see https://github.com/grindtildeath/account-invoicing/pull/4

2017-12-20 16:44 UTC, eLBati approved these changes

2018-03-08 15:53 UTC, grindtildeath commented
@pedrobaeza This PR is hanging still for a while and the module is already in use on a few installations, shouldn't we merge it ?

2018-03-08 18:36 UTC, pedrobaeza commented
We need another reviewer for this one. Can you ask any of your colleagues to review it, or maybe you review another PR and ask in exchange that he/she reviews yours?

2018-03-08 18:37 UTC, pedrobaeza commented
Sorry, I didn't see the first one. We have 2 approvals, so I can merge.

2018-03-08 18:37 UTC, merged