8.0 account invoice line default account
OCA/account-invoicing pull request #23
Opened 2014-10-20 12:05 UTC by jbaudoux

Porting this MP from lp to github
https://code.launchpad.net/~bcim/account-invoicing/7.0-account_invoice_line_default_account

LP description: Extracted account_invoice_line_default_account module version 6.1 from account-financial-tools project and ported to 7.0. I'm pushing this migrated module to this account-invoicing project as this module is for invoicing and is not a financial tool

Ported to 8.0

2014-12-01 15:41 UTC, jgrandguillaume commented
Hi !

Happy to see you over here :) Can you just have a look why Travis is red ?

thanks,

Joël

2014-12-01 16:24 UTC, jbaudoux commented
Hello Joel,
I guess this is because the code was initially for version 7 and can't work in 8 without the changes marked by red cross (Travis failed). After those changes, code seems to work with 8 as you don't have the red cross any more.

2015-05-07 05:47 UTC, eLBati commented
Thanks @jbaudoux 
some PEP8 to fix
```
./account_invoice_line_default_account/__openerp__.py:41:80: E501 line too long (80 > 79 characters)
./account_invoice_line_default_account/model/account_invoice_line.py:28:17: E128 continuation line under-indented for visual indent
./account_invoice_line_default_account/model/account_invoice_line.py:32:17: E128 continuation line under-indented for visual indent
./account_invoice_line_default_account/model/account_invoice_line.py:49:17: E128 continuation line under-indented for visual indent
./account_invoice_line_default_account/model/account_invoice_line.py:54:15: E128 continuation line under-indented for visual indent
./account_invoice_line_default_account/model/account_invoice_line.py:59:15: E128 continuation line under-indented for visual indent
./account_invoice_line_default_account/model/account_invoice_line.py:66:17: E126 continuation line over-indented for hanging indent
```

2015-05-07 09:40 UTC, adrienpeiffer commented on account_invoice_line_default_account/__openerp__.py
> +    'author': 'Therp BV',
Can you add OCA as author like this : Therp BV,Odoo Community Association (OCA)

2015-05-07 09:42 UTC, adrienpeiffer commented on account_invoice_line_default_account/__openerp__.py
> +    'contributors': ['Jacques-Etienne Baudoux <je@bcim.be>'],
Can you extract this into README.rst file

2015-05-07 09:42 UTC, adrienpeiffer commented on account_invoice_line_default_account/__openerp__.py
> +    'description': '''When entering sales or purchase invoices directly, the
Can you extract this into README.rst file

2015-05-07 09:43 UTC, adrienpeiffer commented on account_invoice_line_default_account/__openerp__.py
> +    'version': '7.0.1.0',
I think 1.0 is enought

2015-07-03 13:17 UTC, jbaudoux commented
Hello,
I update this PR with your comments. Hope it can get merged.
kr
J-E

2015-08-28 16:39 UTC, sbidoul commented on account_invoice_line_default_account/README.rst
> +* Jacques-Etienne Baudoux <je@bcim.be> (BCIM sprl)
Add original author in contributors.

2015-08-28 16:40 UTC, sbidoul commented
Can you just update the README according to the OCA template in https://github.com/OCA/maintainer-tools/tree/master/template/module.

Otherwise :+1:

2015-09-11 07:23 UTC, jbaudoux commented
Directory structure and README has been updated

2015-09-18 14:39 UTC, max3903 commented
:+1:

2015-10-01 06:18 UTC, adrienpeiffer commented
@jbaudoux Can you check why travis is red?

2015-10-20 14:42 UTC, jbaudoux commented
It's not related to this module. It's tests in account_invoice_line_sort module that are failing.

2015-12-03 21:45 UTC, jbaudoux commented
Hello,
Can this old PR get merged?

2016-10-04 16:09 UTC, pedrobaeza commented
Travis is still red. @jbaudoux, are you going to work on this?

2016-10-04 19:47 UTC, jbaudoux commented
I think Travis will always be red unless the module account_invoice_line_sort in the branch 8.0 get fixed.

2016-10-14 12:39 UTC, pedrobaeza requested changes

2016-10-14 12:39 UTC, pedrobaeza commented on account_invoice_line_default_account/__openerp__.py
> +    'version': '1.0',
Use 8.0.1.0.0

2016-10-14 12:39 UTC, pedrobaeza commented on account_invoice_line_default_account/i18n/account_invoice_line_default_account.pot
> +# Translation of OpenERP Server.
Remove POT file

2016-10-16 10:19 UTC, pedrobaeza commented
Superseeded by #189

2016-10-16 10:19 UTC, closed without merging