[9.0] New module [purchase_stock_picking_return_invoicing]
OCA/account-invoicing pull request #230
Opened 2017-02-16 15:39 UTC by jbeficent

Refund Returned Pickings from Purchase Orders
=============================================

This module extends the functionality of purchase orders to support marking some
returned pickings as "To refund in Purchase Order",  excluding those quantities
from the quantity to invoice, when the product is to be invoiced based on
received quantities.

Usage
=====

Case 1: When you return to a supplier some products, and you have not yet
received the bill from the supplier

#. Go to *Purchases > Purchase > Purchase Orders > Create*.
#. Choose a supplier and add a product whose *Invoicing Policy* is *On Received
   quantities*, and input some quantity to purchase.
#. Confirm the purchase order.
#. Go to *Shipment > Validate > Apply* so as to receive the quantities ordered.
#. Press the button *Reverse*.
#. In the wizard *Reverse Quantity* Set *Quantity* to the quantity to be
   returned, and check *To Refund*. Press *Return* to complete the wizard.
#. On the return picking press *Validate > Apply*.
#. Go back to the purchase order. You will notice that the field *Received
   Qty* is now the quantity that was originally received, less the quantity
   that was returned.
#. Press the button *Invoices* to create the vendor bill.
#. The proposed vendor bill will be proposed for the difference between the
   received and the returned quantity.

Case 2: When you return to a supplier some products, and you have already
received a bill from the supplier.

#. Go to *Purchases > Purchase > Purchase Orders > Create*.
#. Choose a supplier and add a product whose *Invoicing Policy* is *On Received
   quantities*, and input some quantity to purchase.
#. Confirm the purchase order.
#. Go to *Shipment > Validate > Apply* so as to receive the quantities ordered.
#. Press the button *Invoices* to create the vendor bill.
#. The proposed vendor bill will be proposed for the quantity received. The
   *Invoice Status* is now 'Invoiced'
#. Go to the original incoming shipment
#. Press the button *Reverse*.
#. In the wizard *Reverse Quantity* Set *Quantity* to the quantity to be
   returned, and check *To Refund*. Press *Return* to complete the wizard.
#. On the return picking press *Validate > Apply*.
#. Go back to the purchase order. It will have  *Invoice Status* as 'Waiting
   Invoces'. You will notice that the field *Received Qty* is now the quantity
   that was originally received, less the quantity that was returned.
#. Press the button *Refunds* to create the vendor refund bill.
#. The proposed vendor refund bill will be proposed for the difference between
   the received and the returned quantity.
#. If you back to the purchase order, you will notice that *Invoice Status*
   is now 'Invoiced', even when the quantity ordered does not match with the
   quantity invoiced, because you chose to refund some products.

2017-02-16 15:39 UTC, jbeficent commented
cc @tecnativa @eficent

2017-02-16 15:41 UTC, jbeficent commented
@lreficent @mreficent please review

2017-02-16 17:38 UTC, jbeficent commented
For some strange reason Travis fails in OCB, but I cannot reproduce the error, neither in runbot nor in local.

2017-02-16 20:11 UTC, jbeficent commented
Travis issues an error in the OCB. PR https://github.com/OCA/OCB/pull/590 fixes that.

2017-02-16 23:05 UTC, jbeficent commented
@pedrobaeza Following up on the discussion we had here https://github.com/OCA/OCB/commit/f6ff9771097ad0be27e63f8f968a6fea4bcdf943#commitcomment-20920814

The problem of your proposal to dynamically select invoice or refund is in purchases the supplier invoice is created manually by the user, either from within the PO using just a link. As he adds the PO to the invoice, then the system proposes the invoice lines 'automagically'.

If you have a PO where in line 1 you still need to invoice quantity 1, and line 2 you need to refund quantity 1, the user should create 2 separate invoices. 1 in_invoice, and 1 in_refund.

If you think about it, it makes total sense. The refunds are normally a result of an issue with a product, and are issued once the vendor has already sent a prior invoice. It makes sense that a separate refund is created for those products that have been returned.

2017-02-17 09:27 UTC, LoisRForgeFlow reviewed
Tested on runbot and works fine now! I don't now if the issue with travis will involve some changes though.

2017-02-17 09:27 UTC, lreficent commented on purchase_stock_picking_return_invoicing/models/account_invoice.py
> +        _logger.info(msg)
Is this just for local debug? it should be removed at some point, shouldn't it?

2017-02-20 13:46 UTC, jbeficent commented
Can you review @mreficent?

2017-02-21 08:38 UTC, MiquelRForgeFlow approved these changes
tested on runbot :+1:

2017-02-26 16:37 UTC, pedrobaeza requested changes
Very light code review.

After trying functionally the module, these are the things I see that needs to be improved:

* On "Reverse transfer" dialog, "To refund in PO" column should be hidden for non incoming pickings. The same applies for "To Refund" in the brother module "sale_stock_picking_return_invoicing", but that can be on another module.
* Once you have selected on the dialog if refund or not refund, there's no way of changing this. Can we added somewhere on "Initial demand" page?
* The invoice status doesn't change to "waiting invoices" when returning goods after making the initial invoice.
* There's no visual sign that you need to click on invoices nor refunds for making the operation, but that's also a problem in standard with only invoices.
* The standard "Invoices" smart-button shows both invoices (the normal and the refund one), which is weird, so there are 2 choices:
  1. Change this button to only show normal invoices.
  2. Change the behavior of the normal invoice to change on the fly the invoice type when only having returned quantities.
* What reinforces the choice of the second option is that if you create directly a supplier refund, you are not able to select any purchase order, which indicates that there is some black logic inside the module to get this to work when clicking "Refunds" smart-button.

2017-02-26 16:37 UTC, pedrobaeza commented on purchase_stock_picking_return_invoicing/README.rst
> +returned pickings as "To refund in Purchase Order",  excluding those quantities
"To Refund in PO"

2017-02-26 16:37 UTC, pedrobaeza commented on purchase_stock_picking_return_invoicing/README.rst
> +returned pickings as "To refund in Purchase Order",  excluding those quantities
s/returned pickings/returned picking lines

2017-02-26 16:37 UTC, pedrobaeza commented on purchase_stock_picking_return_invoicing/README.rst
> +   returned, and check *To Refund*. Press *Return* to complete the wizard.
s/To Refund/To Refund in PO

2017-02-26 16:37 UTC, pedrobaeza commented on purchase_stock_picking_return_invoicing/README.rst
> +  v10, plus a fix for https://github.com/odoo/odoo/issues/13974, so this addon
s/v10/v11

2017-02-26 16:37 UTC, pedrobaeza commented on purchase_stock_picking_return_invoicing/models/purchase_order.py
> +        '''
Triple double quota for docstring according PEP257

2017-02-26 16:38 UTC, pedrobaeza commented
@sergio-teruel, please continue reviewing the module and solving the OCB issue.

2017-03-02 18:21 UTC, jbeficent commented
@pedrobaeza @sergio-teruel I removed the field 'to_refund_po' from the return wizard. It does not make sense in the purchasing context to use that indicator. In purchases it is up to the person that validates the supplier invoices to compare the quantities ordered, received, returned with the vendor bill to decide what is acceptable (under the accepted tolerance). This way the process is way more simple and intuitive.

2017-03-03 12:32 UTC, sergio-teruel requested changes

2017-03-03 12:32 UTC, sergio-teruel commented on purchase_stock_picking_return_invoicing/__openerp__.py
> +    "name": "Refund Return Pickings in Purchase Orders",
s/Return/Returned

2017-03-03 12:32 UTC, sergio-teruel commented on purchase_stock_picking_return_invoicing/__openerp__.py
> +    "summary": "Add an option to refund return pickings",
s/return/returned

2017-03-03 12:32 UTC, sergio-teruel commented on purchase_stock_picking_return_invoicing/tests/test_refund.py
> +        cls.partner = cls.env.ref('base.res_partner_1')
If you create a new accounts why not create a new partner and a new product instead of use demo data?? in this way we do not need demo data, so this is better for run tests. :smile:

2017-03-03 13:13 UTC, sergio-teruel commented on purchase_stock_picking_return_invoicing/models/account_invoice.py
> +                     self)._prepare_invoice_line_from_po_line(line)
Why not you use
if data:
    if line.product_id.....

by this way you avoid the OCB Error

2017-03-14 19:01 UTC, luismontalba approved these changes
Tested on runbot

2017-03-15 09:34 UTC, chienandalu approved these changes
- tested functionality

2017-03-15 12:30 UTC, jbeficent commented
Thanks for your reviews so far. We have introduced an important change. New fields are added to the PO line:
* Returned Qty
* Qty to Refund
* Refunded Qty

Now the process is much more clear.

Thanks to @pedrobaeza for the recommendation.

2017-03-20 10:21 UTC, jbeficent commented
@chienandalu @luismontalba @sergio-teruel Can you re-test after the latest changes that we introduced?

2017-03-21 07:52 UTC, sergio-teruel commented on purchase_stock_picking_return_invoicing/models/account_invoice.py
> +                     self)._prepare_invoice_line_from_po_line(line)
@jbeficent I remove this comment after last changes in origin OCB method.

2017-03-21 08:34 UTC, chienandalu approved these changes
The workflow is clearer now indeed. Tested functionality :+1:

2017-03-21 21:00 UTC, luismontalba approved these changes
I've tested it on runbot and it works

2017-03-23 07:55 UTC, pedrobaeza commented
Merging finally. Thanks all for the efforts made.

2017-03-23 07:56 UTC, pedrobaeza approved these changes

2017-03-23 07:57 UTC, merged

2017-06-15 13:24 UTC, ccandito commented
very good.
this covers a huge gap in odoo.
when will it be available in 10?
thanks in advance
claudio candito

2017-06-15 14:17 UTC, pedrobaeza commented
There are no plans for now for that. You can  also contribute with the migration.

2017-06-15 14:22 UTC, ccandito commented
unfortunately I'm not a developer, but I'll test it.
I'd suggest to implement another feature also:
a new field, block payment, to be evaluating manually
in case this is evaluated it is not possible to register the payment.
this field can be evaluated after posting the invoice also.
Regards
claudio candito