[8.0] ADD account_invoice_rounding_by_currency
OCA/account-invoicing pull request #231
Opened 2017-02-17 16:00 UTC by eLBati

Unit rounded invoice (Swedish rounding) by currency
===================================================

This module extends functionality of module Unit rounded invoice https://github.com/OCA/account-invoicing/tree/8.0/account_invoice_rounding

It allows to set, in accounting settings, a rounding precision for each currency,
such as 0.05 CHF for Swiss invoices

Configuration
=============

In Settings -> Configuration -> Accounting you will find
Currencies Rounding Rules
Set currency rule for each currency you need to handle.

- `Swedish Round globally`

  To round your invoice total amount, this option will do the adjustment in
  the most important tax line of your invoice.

- `Swedish Round by adding an invoice line`

  To round your invoice total amount, this option create a invoice line without
  taxes on it. This invoice line is tagged as `is_rounding`

2017-02-19 05:31 UTC, elicoidal requested changes
Thanks for the contribution.
Mostly small details

2017-02-19 05:31 UTC, elicoidal commented on account_invoice_rounding_by_currency/README.rst
> +Unit rounded invoice (Swedish rounding) by currency
Is it officially called "Swedish Rounding"?

2017-02-19 05:31 UTC, elicoidal commented on account_invoice_rounding_by_currency/README.rst
> +such as 0.05 CHF for Swiss invoices
please add a period

2017-02-19 05:31 UTC, elicoidal commented on account_invoice_rounding_by_currency/README.rst
> +In Settings -> Configuration -> Accounting you will find
Please use enumerated list for procedures

2017-02-19 05:31 UTC, elicoidal commented on account_invoice_rounding_by_currency/README.rst
> +  To round your invoice total amount, this option create a invoice line without
"this option will create an invoice line without tax on it."
add a period at the end of the sentence

2017-02-19 05:31 UTC, elicoidal commented on account_invoice_rounding_by_currency/demo/data.xml
> +            <field name="name">IVA a credito 10%</field>
please use English in the xml files and add a translation file

2017-02-19 05:31 UTC, elicoidal commented on account_invoice_rounding_by_currency/models/company.py
> +        "summed, leading to the total amount for that tax. If you "
"summed up" (2 times)

2017-02-19 05:31 UTC, elicoidal commented on account_invoice_rounding_by_currency/tests/test_rounding_by_currencies.py
> +# -*- coding: utf-8 -*-
Please use short headers

2017-02-24 15:59 UTC, eLBati commented on account_invoice_rounding_by_currency/README.rst
> +Unit rounded invoice (Swedish rounding) by currency
Hi @elicoidal the term is already used here https://github.com/OCA/account-invoicing/tree/8.0/account_invoice_rounding

See https://en.wikipedia.org/wiki/Cash_rounding

2017-02-24 16:05 UTC, eLBati commented on account_invoice_rounding_by_currency/models/company.py
> +        "summed, leading to the total amount for that tax. If you "
Doesn't "sum up" mean "give a summary"?

2017-02-24 16:08 UTC, eLBati commented on account_invoice_rounding_by_currency/tests/test_rounding_by_currencies.py
> +# -*- coding: utf-8 -*-
Done

2017-02-24 16:08 UTC, eLBati commented on account_invoice_rounding_by_currency/demo/data.xml
> +            <field name="name">IVA a credito 10%</field>
Done

2017-02-24 16:09 UTC, eLBati commented on account_invoice_rounding_by_currency/README.rst
> +such as 0.05 CHF for Swiss invoices
Done

2017-02-24 16:12 UTC, eLBati commented on account_invoice_rounding_by_currency/README.rst
> +In Settings -> Configuration -> Accounting you will find
done

2017-02-24 16:13 UTC, eLBati commented on account_invoice_rounding_by_currency/README.rst
> +  To round your invoice total amount, this option create a invoice line without
I don't understand this one

2017-02-24 16:13 UTC, eLBati commented
@elicoidal thanks for the review. I made changes

2017-02-25 07:56 UTC, elicoidal commented on account_invoice_rounding_by_currency/README.rst
> +Unit rounded invoice (Swedish rounding) by currency
I see that but it is NZ English ;)
I would suggest to switch to "Cash Rounding" which is more in line with American English used by Odoo.

2017-02-25 07:56 UTC, elicoidal commented on account_invoice_rounding_by_currency/README.rst
> +  To round your invoice total amount, this option create a invoice line without
To round your invoice total amount, this option create a invoice line this option will create an invoice line without tax on it.
This invoice line is tagged as `is_rounding`.
(Period=".")

2017-02-25 07:56 UTC, elicoidal commented on account_invoice_rounding_by_currency/models/company.py
> +        "summed, leading to the total amount for that tax. If you "
It does but you have the other meaning as well. Check #3 here: http://www.thefreedictionary.com/sum+up
"sum up - determine the sum ofsum up - determine the sum of; "Add all the people in this town to those of the neighboring town""

Anyway, I am not here to be picky and I am not native English so it is up to you :)

2017-03-10 15:45 UTC, eLBati commented
@elicoidal thanks, made the changes

2017-10-10 13:20 UTC, eLBati commented
:green_heart: green now

2017-10-16 07:09 UTC, hurrinico commented
Runbot is red, but LGTM :+1:

2017-10-16 07:32 UTC, tafaRU approved these changes

2017-10-16 07:33 UTC, tafaRU commented
@elicoidal, could you please have a final review before to merge it?
Thank you in advance.

2017-10-16 10:31 UTC, elicoidal approved these changes
some unblocking details

2017-10-16 10:31 UTC, elicoidal commented on account_invoice_rounding_by_currency/README.rst
> +Currencies Rounding Rules
I would suggest something like: 
```
#. in Settings > Configuration > Accounting, check Currencies Rounding Rules
#. Set currency rule for each currency you need to handle:

  - `Swedish Round globally`
    To round your invoice total amount, this option will do the adjustment in
    the most important tax line of your invoice.
  - `Swedish Round by adding an invoice line`
    To round your invoice total amount, this option will create a invoice line without
    taxes on it.
    This invoice line is tagged as `is_rounding`

```

2017-10-16 10:31 UTC, elicoidal commented on account_invoice_rounding_by_currency/README.rst
> +
remove extra lines

2017-10-16 10:31 UTC, elicoidal commented on account_invoice_rounding_by_currency/models/company.py
> +            'Currency must be unique per Company!'),
Usually better to avoid the "!" which makes the end user uncomfortable :wink:

2017-10-20 07:03 UTC, eLBati commented
@elicoidal thanks, done

2017-10-20 07:28 UTC, merged