[MIG][9.0] account_invoice_merge_payment module
OCA/account-invoicing pull request #232
Opened 2017-03-02 10:32 UTC by cubells

- Updated README

cc @Tecnativa

2017-03-07 16:58 UTC, rafaelbn commented on account_invoice_merge_payment/README.rst
> +Invoice** in Action button menu.
@cubells I've tested but I don't see this option, check:
![2017-03-07_17-57-29](https://cloud.githubusercontent.com/assets/8736623/23667912/b5edced8-035f-11e7-988c-894b6f060a4c.png)

2017-03-07 16:59 UTC, rafaelbn commented
Please @cubells review travis and runbot in red. Thanks

2017-03-24 14:00 UTC, pedrobaeza requested changes

2017-03-24 14:00 UTC, pedrobaeza commented on account_invoice_merge_payment/README.rst
> +account_payment_partner are installed
2 spaces before for correct indentation

2017-03-24 14:00 UTC, pedrobaeza commented on account_invoice_merge_payment/README.rst
> +Invoice** in Action button menu.
Add that the payment mode will be considered also as merging criteria (with different payment modes they won't be merged) and the merged invoice will have the payment mode filled if they are the same.

2017-03-24 14:00 UTC, pedrobaeza commented on account_invoice_merge_payment/__openerp__.py
> +    'version': '9.0.0.1.0',
9.0.1.0.0

2017-03-28 18:13 UTC, cubells commented on account_invoice_merge_payment/README.rst
> +Invoice** in Action button menu.
done.

2017-03-28 18:13 UTC, cubells commented on account_invoice_merge_payment/__openerp__.py
> +    'version': '9.0.0.1.0',
done.

2017-03-30 09:40 UTC, luismontalba approved these changes
Tested on runbot, it works fine

2017-03-30 16:18 UTC, moylop260 approved these changes

2017-03-30 16:22 UTC, pedrobaeza approved these changes

2017-03-30 16:40 UTC, merged