[FIX] Combining invoices keeps the sale.order.line reference intact
OCA/account-invoicing pull request #236
Opened 2017-03-16 09:23 UTC by RoelAdriaans-B-informed

Because self.env['sale.order'] returns an empty record set, this is evaluated to False.
This in turn never calls the code to restore the link between sale order and invoice.
Because this code was never called in version 9 and above, it never encountered the issue
that the the field invoice_ids is now a computed field without a search.
Searching on that field returned all the sale.orders.
The linked sale_line_ids are now copied like the rest of the fields.

2017-03-16 09:28 UTC, pedrobaeza reviewed
Why not only removing the line `if so_obj`? The rest of the code is there because you can have installed account, but not sale module.

2017-03-16 09:32 UTC, RoelAdriaans-B-informed commented
Because that code doesn't work :)

The so_obj.search([('invoice_ids', 'in', invoices_info[new_invoice_id])]) does a search on invoice_ids, and that's a computed field, without an search option, so that doesn't work. : https://github.com/odoo/odoo/blob/9.0/addons/sale/sale.py#L135

Fixing that is possible, but ends op being a kludge. 
This code also looks if sale is installed, because if sale is not installed, the field sale_line_ids is not available in self.env['account.invoice.line']._fields.

2017-03-16 09:35 UTC, pedrobaeza approved these changes
OK, I see. Thanks for the clarification.

2017-05-31 08:14 UTC, MiquelRForgeFlow requested changes

2017-05-31 08:14 UTC, mreficent commented on account_invoice_merge/models/account_invoice.py
> +        for field in ['analytics_id', 'sale_line_ids']:
The 'analytics_id' field was added by `account_analytic_plans` base module. But this base module was removed in v9. So this field is not anymore in versions 9.0 and then here it should be removed.

2019-01-17 18:27 UTC, RoelAdriaans commented
Closing this merge request. 
Does not merge anymore, and no interest in updating or testing it since 9.0 is pretty old.

2019-01-17 18:27 UTC, closed without merging