[MIG] Migration of account_invoice_merge_purchase to 10.0
OCA/account-invoicing pull request #251
Opened 2017-04-03 10:33 UTC by adrienpeiffer

- [ ] depends on #238

2017-04-03 10:56 UTC, pedrobaeza commented
This has been recently migrated to 9.0, so little changes are needed from that version. Please respect commit history following migration guide: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0

2017-04-03 11:21 UTC, adrienpeiffer commented
@pedrobaeza It's done.

2017-04-03 13:55 UTC, elicoidal approved these changes
nitpicking.
Do you need the setup directory?

2017-04-03 13:55 UTC, elicoidal commented on account_invoice_merge_purchase/README.rst
> +account invoice merge module
Please add a period.

2017-04-03 13:55 UTC, elicoidal commented on account_invoice_merge_purchase/README.rst
> +Select several vendor bills from the same partner and click on **Merge Partner
Please use enumerated list ("#. ")

2017-04-03 13:55 UTC, elicoidal commented on setup/account_invoice_merge_purchase/odoo/__init__.py
> +__import__('pkg_resources').declare_namespace(__name__)
do you really need to have those files?

2017-04-03 14:25 UTC, pedrobaeza approved these changes

2017-04-03 14:25 UTC, pedrobaeza commented
Please check Travis

2017-04-03 14:32 UTC, adrienpeiffer commented
@pedrobaeza Thanks. account_invoice merge is not yet merged.

2017-04-03 14:33 UTC, pedrobaeza commented
Yeah, that's right! OK, let's put this as WIP. You have already my code review approval anyway :wink:

2017-05-30 11:18 UTC, adrienpeiffer commented on setup/account_invoice_merge_purchase/odoo/__init__.py
> +__import__('pkg_resources').declare_namespace(__name__)
yes :smile:

2017-06-14 09:42 UTC, mreficent commented
@adrienpeiffer Can you update this PR, please?

2017-09-13 16:36 UTC, jbeficent commented
@adrienpeiffer Now that  account_invoice merge there are now some errors in Travis.

2017-10-02 16:46 UTC, pedrobaeza commented
A rebase is needed in this PR

2017-10-09 07:19 UTC, adrienpeiffer commented
Rebased

2017-10-10 11:44 UTC, pedrobaeza commented
Travis is still failing. Do you know why?

2017-10-26 11:11 UTC, benwillig approved these changes
LGTM :+1:

2018-03-26 10:25 UTC, lreficent commented
@adrienpeiffer Any update here? Tests are failing.

2018-07-09 10:28 UTC, AaronHForgeFlow requested changes
Tests of this module are failing

2018-07-10 16:33 UTC, rousseldenis commented
@aheficent I'm on it

2018-07-10 17:03 UTC, rousseldenis commented
@aheficent Done. Waiting for travis :sweat_smile:

2018-07-10 18:39 UTC, merged