[10.0][MIG] : account_invoice_customer_ref_uniqe
OCA/account-invoicing pull request #257
Opened 2017-04-14 14:39 UTC by misern2

# USAGE

This module adds a insensitive constraint on the name Customer Reference
(name field): (partner_id, name) must be unique.

2017-09-26 11:46 UTC, AaronHForgeFlow approved these changes
:+1: 
It'll be great a pre-install hook to prevent this constraint to be triggered when installing.

2017-09-26 16:16 UTC, moylop260 requested changes

2017-09-26 16:16 UTC, moylop260 commented on account_invoice_customer_ref_unique/models/account_invoice.py
> +    def _check_unique_name_insensitive(self):
In order to increase the performance is faster use a sql constraint based on computed fields with store=True

2017-09-26 16:16 UTC, moylop260 commented on account_invoice_customer_ref_unique/models/account_invoice.py
> +    def _check_unique_name_insensitive(self):
check the following example where is 4x faster than a python constraint using too many invoices https://github.com/Vauxoo/addons-vauxoo/blob/8.0/supplier_invoice_number_unique/model/account_invoice.py

2017-09-30 09:51 UTC, misern2 commented
@moylop260 Thanks for your revision. I pushed a new commit with the SQL Constraints

2017-09-30 12:47 UTC, moylop260 commented on account_invoice_customer_ref_unique/models/account_invoice.py
> +         'customer_ref_strip, company_id, partner_id)',
s/partner_id/commercial_partner_id/g` in order to supports the case where other address is used for the same partner

2017-09-30 12:49 UTC, moylop260 requested changes
LGTM just small changes.

And check our beta message of the lint build:
https://travis-ci.org/OCA/account-invoicing/jobs/281607391#L743

```bash
************* Module account_invoice_customer_ref_unique
account_invoice_customer_ref_unique/README.rst:32: [E7901(rst-syntax-error), ]  Unexpected possible title overline or transition.|Treating it as ordinary text because it's so short.
account_invoice_customer_ref_unique/README.rst:1: [W7908(missing-newline-extrafiles), ]  Missing newline
************* Module account_invoice_customer_ref_unique.__manifest__
account_invoice_customer_ref_unique/__manifest__.py:1: [C8201(no-utf8-coding-comment), ] No UTF-8 coding comment found: Use `# coding: utf-8` or `# -*- coding: utf-8 -*-`
account_invoice_customer_ref_unique/__manifest__.py:23: [C8103(manifest-deprecated-key), ] Deprecated key "description" in manifest file
************* Module account_invoice_customer_ref_unique.models.account_invoice
account_invoice_customer_ref_unique/models/account_invoice.py:1: [C8201(no-utf8-coding-comment), ] No UTF-8 coding comment found: Use `# coding: utf-8` or `# -*- coding: utf-8 -*-`
```

2017-09-30 12:49 UTC, moylop260 commented on .travis.yml
> +  - "2.7"
remove this small change

2017-09-30 12:50 UTC, moylop260 commented
...and create a hook to auto-fix all current wrong info breaking the constraint:
https://travis-ci.org/OCA/account-invoicing/jobs/281607395#L1407

2017-09-30 19:52 UTC, misern2 commented
@moylop260 I think it's all finshed. I also checked the travis log file and now  there is not any error beta message.
Thanks.

2017-09-30 21:24 UTC, moylop260 requested changes
Sorry I didn't see this before...

Thanks for your great work!

2017-09-30 21:24 UTC, moylop260 commented on account_invoice_customer_ref_unique/__init__.py
> +from . import models
Missing newline

2017-09-30 21:24 UTC, moylop260 commented on account_invoice_customer_ref_unique/__init__.py
>  ##############################################################################
Use shortest license like as template module:
https://github.com/OCA/maintainer-tools/blob/master/template/module/models/model_name.py#L2

2017-09-30 21:24 UTC, moylop260 commented on account_invoice_customer_ref_unique/README.rst
> +To contribute to this module, please visit https://odoo-community.org.
missing newline

2017-09-30 21:24 UTC, moylop260 commented on account_invoice_customer_ref_unique/README.rst
> +
Remove unused sections

2017-09-30 21:24 UTC, moylop260 commented on account_invoice_customer_ref_unique/models/account_invoice.py
> +# #############################################################################
Short license

2017-10-02 16:46 UTC, houssine78 commented on account_invoice_customer_ref_unique/models/account_invoice.py
> +            if invoice_type not in ['out_invoice', 'out_refund']:
maybe we can remove the previous line as the invoice_type variable is only used once in the if statement

2017-10-02 19:03 UTC, misern2 commented
Changes requested.
The travis build on my branch was Ok and It fails on this PR in my last commit. Am I missing something ?

2017-10-02 21:19 UTC, houssine78 approved these changes

2017-10-03 06:12 UTC, pedrobaeza commented
Travis is red

2022-05-01 12:15 UTC, closed without merging