[9.0][account_invoice_merge] fix error + backport test cases from 10.0
OCA/account-invoicing pull request #301
Opened 2017-08-08 17:11 UTC by jbeficent

- backports test cases from 10.0
- fixes error 'Non-stored field sale.order.invoice_ids cannot be searched'

2017-08-09 14:53 UTC, AaronHForgeFlow approved these changes
:+1: Code review

2017-08-14 11:10 UTC, LoisRForgeFlow approved these changes
LGTM :+1:

2017-08-14 11:11 UTC, pedrobaeza requested changes
Change version number

2017-08-24 15:01 UTC, MiquelRForgeFlow approved these changes

2017-08-24 15:05 UTC, pedrobaeza approved these changes

2017-08-24 15:05 UTC, merged