account_invoice_from_picking initial commit
OCA/account-invoicing pull request #320
Opened 2017-10-13 14:24 UTC by rvalyi

Module to allows to create invoice lines from picking orders.

An usage of this module is it allows you to create partial invoices for partial receipts/deliveries in case you forgot to create them after each receipt/delivery. Care has been taken for not creating discrepancies with the normal invoices created from the sale orders or pulling lines from the purchase order.

This might be required in some federal countries such as Brazil were you may produce invoice like documents (a bit like European intrastat but with accounting entries too) when you simply move goods from one state to another without sale or purchase order.

This a work in progress as there is still a bug: you can still pull lines from pickings related to paid sale orders. And tests are still missing.

2018-12-27 18:48 UTC, mbcosta commented
I included the dependency of module onchange_helper ( to get the dictionary created by onchanges methods ), but the module has a problem with o2m fields, solved in this PR https://github.com/OCA/server-tools/pull/1468 . So this PR depends of the fix on onchange_helper module first.

cc @rvalyi @renatonlima @mileo

2019-04-15 23:39 UTC, mileo commented
Some fix: https://github.com/akretion/account-invoicing/pull/6

2019-04-16 13:28 UTC, mileo commented
Hi, i detect some issue when insert the product 

https://www.youtube.com/watch?v=tHHJkgsMBco

2019-04-16 16:56 UTC, mileo requested changes
See video

2019-05-02 16:15 UTC, aheficent commented
From my side this works well, I created a fix for a minor issue I found https://github.com/akretion/account-invoicing/pull/7

As this is PR is quite old, also a rebase would be good.

Thanks

2019-05-03 04:21 UTC, nikul-serpentcs requested changes
nitpicking

2019-05-03 04:21 UTC, nikul-serpentcs commented on account_invoice_from_picking/README.rst
> +Known issues / Roadmap
@rvalyi  If not any  Roadmap content then remove it.

2019-05-03 04:21 UTC, nikul-serpentcs commented on account_invoice_from_picking/README.rst
> +* Firstname Lastname <email.address@example.org>
@rvalyi Can you please add your name

2019-05-03 04:21 UTC, nikul-serpentcs commented on account_invoice_from_picking/README.rst
> +* Company 1 name
?

2019-05-03 04:21 UTC, nikul-serpentcs commented on account_invoice_from_picking/__manifest__.py
> +    'website': 'www.akretion.com',
URL should be `https://github.com/OCA/account-invoicing`

2019-05-03 04:21 UTC, nikul-serpentcs commented on account_invoice_from_picking/models/account_invoice.py
> +        string='Add Picking Order',
```suggestion
        string="Picking Order"
```

2019-05-03 04:21 UTC, nikul-serpentcs commented on account_invoice_from_picking/models/stock.py
> +        for picking_id in active_ids:
```suggestion
        for picking_id in self.env['stock.picking'].browse(active_ids):
```

2019-05-07 21:07 UTC, mbcosta commented
Hi @mileo @aheficent @nikul-serpentcs thanks for reviews

At 3 weeks ago we noticed that there is other PR in the repo with same purpose https://github.com/OCA/account-invoicing/pull/509 , so I think the first thing to do should be choose one of them or try to join the best parts of the both code.

cc @rvalyi @renatonlima

2019-07-11 15:30 UTC, rvalyi commented
superseded by https://github.com/OCA/account-invoicing/pull/509

2019-07-11 15:30 UTC, closed without merging