[11.0][MIG] account_payment_term_extension
OCA/account-invoicing pull request #328
Opened 2017-11-13 17:50 UTC by NachoSerra

2017-11-14 16:04 UTC, pedrobaeza commented
Please squash together all "OCA Transbot..." commits.

2018-01-06 22:55 UTC, melroy89 requested changes
You can remove the utf-8 lines from the top in Python3. Just safe the file in utf8 format.

2018-01-06 22:55 UTC, danger89 commented on account_payment_term_extension/__init__.py
> +# -*- coding: utf-8 -*-
You can remove the utf-8 lines from the top in Python3. Just safe the file in utf8 format.

2018-01-06 22:55 UTC, danger89 commented on account_payment_term_extension/models/account_payment_term.py
> +# -*- coding: utf-8 -*-
You can remove the utf-8 lines from the top in Python3. Just safe the file in utf8 format.

2018-01-06 22:55 UTC, danger89 commented on account_payment_term_extension/tests/test_account_payment_term_multi_day.py
> +# -*- coding: utf-8 -*-
same..

2018-02-12 14:01 UTC, pmartineznetquest approved these changes
LGTM in these scenarios:
- a payment term with a single payment date. ok
- a payment term with 2 payment dates. ok
- changing from 1 payment term to another recalculates the Due Date. ok
- changin invoice partner changes and recalculates Due Date. ok

2018-03-16 14:04 UTC, angelmoya approved these changes
Some remarks but LGTM

2018-03-16 14:04 UTC, angelmoya commented on account_payment_term_extension/README.rst
> +   :target: https://runbot.odoo-community.org/runbot/95/10.0
11.0

2018-03-16 14:04 UTC, angelmoya commented on account_payment_term_extension/i18n/es.po
> +msgstr "60 dias al final del mes"
Días

2018-03-16 14:04 UTC, angelmoya commented on account_payment_term_extension/i18n/es.po
> +msgstr "Numero de meses"
Número

2018-03-16 14:04 UTC, angelmoya commented on account_payment_term_extension/i18n/es_ES.po
> +msgstr "60 dias al final del mes"
Días

2018-03-16 14:04 UTC, angelmoya commented on account_payment_term_extension/i18n/es_ES.po
> +msgstr "Numero de meses"
Número

2018-03-16 14:04 UTC, angelmoya commented on account_payment_term_extension/models/account_payment_term.py
> +                payment_days.sort()
decode_payment_days call days.sort() before return, so you can delete this line

2018-03-19 17:24 UTC, pedrobaeza commented
@NachoSerra are you going to finish this?

2018-04-16 19:04 UTC, pedrobaeza commented
Superseeded by #375

2018-04-16 19:04 UTC, closed without merging