[11.0] [MIG] account_invoice_check_total: Migration to 11.0
OCA/account-invoicing pull request #363
Opened 2018-03-05 20:04 UTC by rven

2018-03-05 22:36 UTC, pedrobaeza commented
The same about squashing adjacent translation commits

2018-03-06 07:48 UTC, rven commented
@pedrobaeza Do I need to squash "Launchpad automatic translations update." also, or only the "OCA Transbot updated translations from Transifex"

2018-03-06 09:54 UTC, pedrobaeza commented
Both, please. I see also a lot of useless commits from the same author at the beginning that you can join by logical set. This way, we reduce the footprint of the repository.

2018-03-09 09:10 UTC, angelmoya requested changes
Tested on runbot, on account settings, "Check Total on Vendor Bills" is shown as Enterprise

2018-03-09 09:11 UTC, angelmoya commented
![settings odoo](https://user-images.githubusercontent.com/6750341/37199509-290f4a34-2382-11e8-9685-9f316641a49e.png)

2018-03-09 18:46 UTC, rven commented
@angelmoya I removed the Enterprise label from the setting

2018-03-16 13:01 UTC, adrian-pesol approved these changes

2018-03-18 06:25 UTC, feketemihai requested changes

2018-03-18 06:25 UTC, feketemihai commented on account_invoice_check_total/README.rst
> +   :target: https://runbot.odoo-community.org/runbot/95/10.0
Can you update runbot version.

2018-03-19 08:53 UTC, rven commented on account_invoice_check_total/README.rst
> +   :target: https://runbot.odoo-community.org/runbot/95/10.0
@feketemihai Done!

2018-03-19 09:37 UTC, feketemihai approved these changes

2018-03-27 17:39 UTC, angelmoya approved these changes

2018-03-27 17:40 UTC, merged