11.0 mig account invoice line description
OCA/account-invoicing pull request #387
Opened 2018-06-11 12:53 UTC by amcor

2018-06-11 12:57 UTC, pedrobaeza commented
Please squash together adjacent "OCA Transbot.." commits and some of other useless commits from same author (or the "...en.po..." one with the translations) using https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests

2018-06-11 13:32 UTC, astirpe requested changes

2018-06-11 13:32 UTC, astirpe commented on account_invoice_line_description/README.rst
> +   :target: https://runbot.odoo-community.org/runbot/95/10.0
11.0

2018-06-11 13:32 UTC, astirpe commented on account_invoice_line_description/__manifest__.py
> +    'name': "Account invoice line description",
Do not mix single apex with double apex in manifest

2018-06-12 12:43 UTC, astirpe approved these changes

2018-06-12 13:18 UTC, pedrobaeza approved these changes

2018-06-12 14:40 UTC, merged