[12.0] [MIG] Account Invoice Supplier Ref Unique
OCA/account-invoicing pull request #433
Opened 2018-10-02 11:25 UTC by ThomasBinsfeld

Migration of account_invoice_supplier_ref_unique from 11.0 to 12.0.
#427

2018-10-02 12:22 UTC, acsonefho reviewed
Only one comment otherwise LGTM (about code)

2018-10-02 12:22 UTC, acsonefho commented on account_invoice_supplier_ref_unique/models/account_invoice.py
> +            same_supplier_inv_num = self.search([
`api.one` is not bad but you have a `search` inside of this function.
A good improvement could be to use `api.multi` and do only a unique `search`.

2018-10-04 08:50 UTC, tafaRU commented
@ThomasBinsfeld, please restart Travis build jobs now that branch `12.0` has been created.

2018-10-12 12:46 UTC, adrienpeiffer commented on account_invoice_supplier_ref_unique/models/account_invoice.py
> +            same_supplier_inv_num = self.search([
@acsonefho As some fields on the invoice record are given to the search method domain parameters, even with a ```api.multi``` we should call the search method for each invoice no ?

2019-01-02 08:52 UTC, jeroen7s commented
can this be merged?

2019-01-02 08:54 UTC, pedrobaeza commented
@jeroen7s if you add your review to this PR, this will help to be merged.

2019-02-11 13:50 UTC, rven commented
@ThomasBinsfeld  Can you please rebase this PR?

2019-02-11 14:12 UTC, ThomasBinsfeld commented
@rven Rebased

2019-02-11 14:18 UTC, rven approved these changes

2019-06-18 14:29 UTC, yung-wang commented
Do we still need this module? I tested it in Runbot V12 with standard Odoo CE and it works out of the box.
![image](https://user-images.githubusercontent.com/30628967/59692911-39383000-91e6-11e9-9b9f-0f746b930412.png)

2019-06-18 15:01 UTC, sbidoul commented
Interesting that Odoo implemented such a check.
The problem is Odoo conflates the supplier invoice number and reference (usually used as payment reference).
This module reintroduce the supplier invoice number and implements the unicity check on that.
The reference remain free and is used as payment reference.

This is particularly useful in presence of structured payment communications.

2019-06-19 12:41 UTC, sebalix approved these changes

2019-06-19 12:41 UTC, sebalix commented on account_invoice_supplier_ref_unique/tests/test_account_invoice_supplier_ref_unique.py
> +        super(TestAccountInvoiceSupplierRefUnique, self).setUpClass()
Small points:
- rename `self` to `cls`
- `super()` parameters could be removed
- very extra: `tracking_disable` context key could be added to `env`

But not blocking

2019-08-07 14:19 UTC, mreficent commented
@ThomasBinsfeld could you apply @sebalix comment?

2019-08-12 12:44 UTC, Tardo requested changes

2019-08-12 12:44 UTC, Tardo commented on account_invoice_supplier_ref_unique/models/account_invoice.py
> +    @api.one
Deprecated since version 9.0

2019-08-12 12:44 UTC, Tardo commented on account_invoice_supplier_ref_unique/models/account_invoice.py
> +        if invoice and invoice.type in ['in_invoice', 'in_refund'] and\
```suggestion
        if invoice and invoice.type in {'in_invoice', 'in_refund'} and\
```

2019-08-12 12:44 UTC, Tardo commented on account_invoice_supplier_ref_unique/models/account_invoice.py
> +        if self.type in ['in_invoice', 'in_refund']:
```suggestion
        if self.type in {'in_invoice', 'in_refund'}:
```

2019-09-23 13:20 UTC, jaumeplanas commented
Any news for this addon? May it be merged?

2019-10-30 13:11 UTC, astirpe commented
This one can be closed. Superseded.

2019-10-30 18:20 UTC, closed without merging