[MIG] purchase_batch_invoicing: Migration to 11.0
OCA/account-invoicing pull request #445
Opened 2018-10-29 13:41 UTC by chienandalu

This module extends the functionality of purchases to support batch invoicing
purchase orders and to allow you to choose if you want them grouped by purchase
order or by vendor.

cc @Tecnativa

2018-11-05 16:50 UTC, pedrobaeza requested changes

2018-11-05 16:50 UTC, pedrobaeza commented on purchase_batch_invoicing/data/ir_cron_data.xml
> +        <field name="active">True</field>
Please don't change this field. Leave it disabled (and it has to be evaluated with `eval`).

2018-11-05 16:50 UTC, pedrobaeza commented on purchase_batch_invoicing/readme/ROADMAP.rst
> +It would be nice to be able to group invoices by PO line.
Put `* ` to start bullet list (although with only one element).

2018-11-05 16:50 UTC, pedrobaeza commented on purchase_batch_invoicing/readme/USAGE.rst
> +#. Have *Purchase / User* permissions.
This point should go to `Configuration` section IMO.

2018-11-05 16:50 UTC, pedrobaeza commented on purchase_batch_invoicing/tests/test_invoicing.py
> +            picking.force_assign()
This shouldn't be needed on receptions

2018-11-06 10:15 UTC, yajo approved these changes

2018-11-06 10:15 UTC, Yajo commented on purchase_batch_invoicing/tests/test_invoicing.py
>  import mock
AFAIK in py3 it is `from unittest import mock`

2018-11-07 10:03 UTC, chienandalu commented
@pedrobaeza Changes done

2018-11-07 23:40 UTC, pedrobaeza approved these changes

2018-11-07 23:40 UTC, merged

2019-02-19 12:03 UTC, rafaelbn commented
@chienandalu take care of https://github.com/OCA/account-invoicing/pull/384 in v9 that affects in v11 too

2019-02-19 12:18 UTC, pedrobaeza commented
Already done in #505, so don't duplicate efforts.