[12.0] [MIG] [WIP] purchase stock picking return invoicing
OCA/account-invoicing pull request #460
Opened 2018-12-05 08:54 UTC by antoniorubiopesol

2018-12-05 09:01 UTC, pedrobaeza commented
Please squash all your migration commits and let the CIs in green.

2019-07-04 14:15 UTC, traviswaelbro commented
@pedrobaeza Can this be merged?

2019-07-04 14:20 UTC, aheficent commented
History is broken, no commits before migration and changes in other modules :confused:

2019-07-04 18:26 UTC, traviswaelbro requested changes

2019-07-04 18:26 UTC, traviswaelbro commented on purchase_stock_picking_return_invoicing/views/purchase_view.xml
> +                       invisible="not context.get('show_purchase', False)"/>
This doesn't appear to work in Odoo 12. Instead, we can mirror the `attrs` used in core's Purchase Order form.

```suggestion
                       attrs="{'column_invisible': [('parent.state', 'not in', ('purchase', 'done'))]}"/>
```

2019-07-04 18:26 UTC, traviswaelbro commented on purchase_stock_picking_return_invoicing/views/purchase_view.xml
> +                       invisible="not context.get('show_purchase', False)"/>
This doesn't appear to work in Odoo 12. Instead, we can mirror the `attrs` used in core's Purchase Order form.

```suggestion
                       attrs="{'column_invisible': [('parent.state', 'not in', ('purchase', 'done'))]}"/>
```

2019-07-04 18:26 UTC, traviswaelbro commented on sale_timesheet_invoice_description/i18n/ar.po
> +<<<<<<< HEAD
Lots of leftover git conflict markers throughout the translation files.

```suggestion
```

2019-07-09 06:29 UTC, jbeficent commented
@ageficent @hveficent @aheficent can you eview this one? I have an open PR in V11 with a change

2019-07-09 07:28 UTC, AdriaGForgeFlow requested changes
Some comments:

Columns Returned Qty and Refunded Qty are not being displayed in the form view.
![image](https://user-images.githubusercontent.com/44768500/60867231-a27df280-a22a-11e9-90e4-cced14f30566.png)

In Use Case 2 (according to Readme) after returning some quantities the Refunds button does not appear.
![Peek 2019-07-09 09-21](https://user-images.githubusercontent.com/44768500/60867712-cb52b780-a22b-11e9-84e8-a2d844d545f1.gif)

There are some files from different modules that do not belong here (sale_timesheet_invoice_description)

2019-07-09 07:49 UTC, pedrobaeza commented
Please superseed this as this doesn't contain commit history, which has been requested several times, and there seems to be no intention on fixing it.

2019-07-09 08:11 UTC, aheficent commented
Apart of the issues already commented I do not get the purpose of this button (I don't know if this is introduced here but in runbot for OCA/account-invoicing for 12.0 this button is not there)
![image](https://user-images.githubusercontent.com/19620251/60870519-53878b80-a231-11e9-91cc-0a7131d4347e.png)

It lists all invoices for all suppliers, it seems to me this is not expected, and there is no explanation for the user.

2019-07-09 12:37 UTC, jbeficent commented
Looks like @antoniorubiopesol is not working on this PR anymore. I suggest that @ageficent @aheficent create a separate PR where the commit history is preserved.

2019-07-09 12:40 UTC, ageficent commented
> Looks like @antoniorubiopesol is not working on this PR anymore. I suggest that @ageficent @aheficent create a separate PR where the commit history is preserved.

On it :+1:

2019-07-09 13:38 UTC, closed without merging