[12.0] [MIG] account_invoice_fiscal_position_update
OCA/account-invoicing pull request #465
Opened 2018-12-17 07:56 UTC by bjeficent

Bump to version 12.0

2019-03-07 12:53 UTC, cubells requested changes
Minor changes. Ready to approve.

2019-03-07 12:53 UTC, cubells commented on account_invoice_fiscal_position_update/__manifest__.py
> +# © 2018 Roel Adriaans <roel@road-support.nl>
change `©` by `Copyright` please.

2019-03-07 12:53 UTC, cubells commented on account_invoice_fiscal_position_update/models/account_invoice.py
> +# © 2014 Akretion (http://www.akretion.com)
Change `©` by `Copyright` please.

2019-03-07 12:53 UTC, cubells commented on account_invoice_fiscal_position_update/models/account_invoice.py
> +from odoo import models, api, _
change order please: `from odoo import _, api, moddels`

2019-03-07 12:53 UTC, cubells commented on account_invoice_fiscal_position_update/tests/test_inv_fiscal_pos_update.py
> +# © 2014 ToDay Akretion (http://www.akretion.com)
Change `©` by `Copyright` please.

2019-03-07 13:03 UTC, bjeficent commented
Comments attended, thanks for reviewing.

2019-03-07 14:28 UTC, legalsylvain commented
Hi @bjeficent. Thanks for porting this module.
Just a question, I don't understand why this module recompute account (income / expense) and write it on each line. AFAIK, the income / expense account doens't depends on fiscal positions. FP are just about taxes.
I think it should be better to separate the two features
- update taxes (account_invoice_fiscal_position_update)
- Reset accounts (account_invoice_account_reset)

Don't you think ?

Thanks for the explanation.

2019-03-07 16:38 UTC, legalsylvain approved these changes

2019-03-13 15:56 UTC, merged

2020-11-19 22:42 UTC, alexis-via commented
The filter of lines on display_type for forgotten in this PR. The display_type field on invoice lines was introduced in v12.