[12.0][MIG] account_invoice_reimbursable
OCA/account-invoicing pull request #538
Opened 2019-06-11 03:21 UTC by saranl-ecosoft

Work in progress.

2019-06-12 13:28 UTC, tbaden requested changes
thanks for the work 👍 
I did a code review: LGTM just something minor

2019-06-12 13:28 UTC, tbaden commented on account_invoice_reimbursable/views/report_invoice.xml
> +</odoo>
please add missing newline

2019-06-12 13:28 UTC, tbaden commented on account_invoice_reimbursable/views/account_invoice_view.xml
> +</odoo>
please add missing newline

2019-06-13 08:42 UTC, Saran440 commented
Fixed it. 
@tbaden Thank you for your reviewed.

2019-06-13 18:46 UTC, tbaden approved these changes

2019-06-27 16:25 UTC, jarroyomorales approved these changes

2019-08-26 06:57 UTC, jarroyomorales commented
@pedrobaeza Can this be merged?

2019-08-26 07:42 UTC, pedrobaeza commented
OK, merging blindly due to 2 reviews.

/ocabot merge

2019-08-26 08:07 UTC, closed without merging