[11.0][MIG] product_supplierinfo_for_customer_invoice
OCA/account-invoicing pull request #611
Opened 2019-10-11 16:00 UTC by mreficent

Standard migration.

2019-10-14 08:01 UTC, AaronHForgeFlow requested changes

2019-10-14 08:01 UTC, aheficent commented on product_supplierinfo_for_customer_invoice/models/account_invoice.py
> +            code_id = product_supplierinfo_obj.search([
Does not look good to me. I created a customer invoice and the customer code in the invoice was totally incorrect.

It should filter by the customer, and also the product.supplierinfo must be type customer

2019-10-14 14:11 UTC, AaronHForgeFlow requested changes

2019-10-14 14:11 UTC, aheficent commented on product_supplierinfo_for_customer_invoice/models/account_invoice.py
> +                ('type', '=', 'customer'),
`supplierinfo_type`

2019-10-14 15:47 UTC, AaronHForgeFlow approved these changes
LGTM now

![merge_small](https://user-images.githubusercontent.com/19620251/66764687-9bf6bb00-eeaa-11e9-8895-eb7336bb40fd.jpg)

2019-10-19 04:57 UTC, nikul-serpentcs approved these changes
Perfecto :+1:

2019-10-19 15:35 UTC, aheficent commented
/ocabot merge

2019-10-19 15:55 UTC, merged