[ADD] account_invoice_date_due: Date Due now could be updated
OCA/account-invoicing pull request #632
Opened 2019-11-14 01:33 UTC by luistorresm

Allow update the date due in an invoice (Even if it's done). To avoid
cancel the invoice and generate again

2019-11-14 01:34 UTC, luistorresm commented
@moylop260 @hugho-ad @luisg123v


Could you approve this PR, please?

Regards

2019-11-14 05:18 UTC, moylop260 approved these changes

2019-11-14 15:42 UTC, hugho-ad approved these changes

2019-11-14 16:28 UTC, luisg123v requested changes
Just some typos and semantical errors.

CC @tomeyro, feel free to correct me if I'm wrong.

2019-11-14 16:28 UTC, luisg123v commented on account_invoice_date_due/__manifest__.py
> +    "name": "Update Invoice Date Due",
Update Invoice's Due Date

2019-11-14 16:28 UTC, luisg123v commented on account_invoice_date_due/README.rst
> +This module adds a wizard in the invoice menu to allow update the invoice
To allow updating

2019-11-14 16:28 UTC, luisg123v commented on account_invoice_date_due/README.rst
> +date due (Even if it's done).
- Due date
- "Done"?

2019-11-14 16:28 UTC, luisg123v commented on account_invoice_date_due/README.rst
> +With this wizard is updated the date due in the invoice and in the journal
When this wizard is used, the invoice's due date is updated, along with the journal entry.

2019-11-14 16:28 UTC, luisg123v commented on account_invoice_date_due/README.rst
> +To enable the wizard is necessary assign the access to the group
To be able to use this wizard, the user needs to have access to the group

2019-11-14 16:28 UTC, luisg123v commented on account_invoice_date_due/__init__.py
> +# -*- coding: utf-8 -*-
Remove encoding.

2019-11-14 16:28 UTC, luisg123v commented on account_invoice_date_due/__manifest__.py
> +# -*- coding: utf-8 -*-
Remove encoding.

2019-11-14 16:28 UTC, luisg123v commented on account_invoice_date_due/wizards/update_due_date.py
> +        help="New date to set in the invoice date due.")
New date to be set to the invoice's due date

2019-11-14 16:41 UTC, luisg123v requested changes

2019-11-14 16:41 UTC, luisg123v commented on account_invoice_date_due/__manifest__.py
> +    "category": "Accouting",
Accounting

2019-11-14 16:41 UTC, luisg123v commented on account_invoice_date_due/wizards/__init__.py
> +# -*- coding: utf-8 -*-
Remove encoding.

2019-11-14 16:41 UTC, luisg123v commented on account_invoice_date_due/README.rst
> +Update Invoice Date Due
Update Invoice's Due Date.

2019-11-14 16:44 UTC, luisg123v commented
Commit's title:
Due date may now be changed.

2019-11-14 19:21 UTC, luistorresm commented
Done @luisg123v 

Thanks.

2019-11-14 20:03 UTC, luisg123v commented on account_invoice_date_due/README.rst
> +date due (Even if it's done).
@luistorresm
This is not applied yet.

2019-11-14 20:07 UTC, luisg123v commented on account_invoice_date_due/README.rst
> +.. image:: https://img.shields.io/badge/licence-AGPL--3-blue.svg
The manifest and some headers say the license is LGPL, but here in the README and some other headers say AGPL.

2019-11-14 22:49 UTC, luistorresm commented on account_invoice_date_due/README.rst
> +date due (Even if it's done).
This was updated.

2020-03-12 04:22 UTC, kittiu commented
/ocabot merge

2020-03-12 07:15 UTC, merged

2020-03-12 17:14 UTC, luisg123v commented
I'm addressing pending comments of this PR on https://github.com/OCA/account-invoicing/pull/689