[10.0][ADD] account_invoice_positive_total
OCA/account-invoicing pull request #645
Opened 2019-12-12 15:08 UTC by acsonefho

Module used to check if the total of OUT invoice/refund is positive. If it's not the case, an exception is raised. It doesn't check IN invoice/refund

2019-12-12 15:47 UTC, Cedric-Pigeon requested changes

2019-12-12 15:47 UTC, Cedric-Pigeon commented on account_invoice_positive_total/__manifest__.py
> +    'summary': "Invoices/Refunds can be validated if the total is positive.",
only if...

2019-12-18 15:57 UTC, baimont approved these changes

2019-12-18 15:57 UTC, baimont commented on account_invoice_positive_total/tests/test_account_invoice.py
> +class TestAccountInvoice(TransactionCase):
Why use TranactionCase and not SavepointCase?
Wouldn't you have faster tests with SavepointCase?

2023-01-01 12:13 UTC, closed without merging