[13.0][MIG][WIP] account_invoice_line_description
OCA/account-invoicing pull request #646
Opened 2019-12-16 03:54 UTC by kongrattapong

2020-03-12 04:09 UTC, kittiu approved these changes
Functional tested, LGTM :+1:

2021-01-12 14:05 UTC, SimoneVagile approved these changes

2021-01-12 14:09 UTC, SimoneVagile commented
This can be merged?

2021-01-12 19:09 UTC, HaraldPanten approved these changes
LGTM

2021-01-13 01:48 UTC, kittiu commented
/ocabot merge nobump

2021-03-18 08:21 UTC, anasuarez1 approved these changes
Functional review LGTM!

Since everything looks ok can we get this merged?

2021-11-03 10:06 UTC, dreispt commented
/ocabot merge nobump

2022-01-10 18:13 UTC, ernestotejeda requested changes
Hello @kongrattapong , thanks for the migration. 
During the merge there was an error, you must rebase and rerun the pre-commit.
I also have some change suggestionshere. 
If you can't continue with the PR, just let me know and I'll open a new one :), thanks.

2022-01-10 18:13 UTC, ernestotejeda commented on account_invoice_line_description/__manifest__.py
> +    "author": "Agile Business Group, " "Tecnativa, " "Odoo Community Association (OCA)",
```suggestion
    "author": "Agile Business Group, Tecnativa, Odoo Community Association (OCA)",
```

2022-01-10 18:13 UTC, ernestotejeda commented on account_invoice_line_description/models/account_move.py
> +class AccountMove(models.Model):
```suggestion
class AccountMoveLine(models.Model):
```

2022-01-10 18:13 UTC, ernestotejeda commented on account_invoice_line_description/models/account_move.py
> +        res = super(AccountMove, self)._onchange_product_id()
```suggestion
        res = super()._onchange_product_id()
```

2022-01-10 18:13 UTC, ernestotejeda commented on account_invoice_line_description/models/account_move.py
> +            )
```suggestion
            product = self.product_id.with_context(lang=self.move_id.partner_id.lang)
            if self.is_purchase_document():
                self.name = product.description_purchase or self.name
            elif self.is_sale_document():
                self.name = product.description_sale or self.name
```
In this way, the name of the account.move of type 'entry' is not changed.

2022-01-10 18:13 UTC, ernestotejeda commented on account_invoice_line_description/wizards/res_config.py
> +        string="Allow using only the product description on the invoice lines",
I think we should change this string value, it's to long IMO and is the same as the help.

2022-01-14 07:25 UTC, pedrobaeza commented
Superseded by #1077

2022-01-14 07:25 UTC, closed without merging