[WIP][MIG][13.0] purchase_batch_invoicing: Migration
OCA/account-invoicing pull request #691
Opened 2020-03-17 16:38 UTC by sergio-teruel

TT21650

2020-03-19 08:39 UTC, yajo requested changes
Seems good overall, just one red alert :yum:

2020-03-19 08:39 UTC, Yajo commented on purchase_batch_invoicing/tests/test_invoicing.py
> +@tagged("post_install", "-at_install")
If it's possible you should avoid this. Post-install tests usually break in integration environments:

```suggestion
```

2020-10-05 18:09 UTC, pedrobaeza approved these changes
Fix a little problem, but working correctly

2020-10-05 18:10 UTC, pedrobaeza commented
As @Yajo said that is good for him, let's merge it as it's very old:

/ocabot merge nobump

2020-10-05 18:59 UTC, merged