[12.0][FIX] Copy purchase data from picking to invoice.
OCA/account-invoicing pull request #713
Opened 2020-05-14 19:53 UTC by mbcosta

Copy purchase data from picking to invoice.

2020-05-14 20:30 UTC, rvalyi requested changes
there is no such purchase_id field with the stock_picking_invoicing and its dependencies. Indeed, it doesn't depend on purchase nor purchase_stock. You can check for yourself: no purchase_id in https://github.com/odoo/odoo/blob/12.0/addons/stock/models/stock_picking.py
On the contrary this field is brought by the purchase_stock module:
https://github.com/odoo/odoo/blob/12.0/addons/purchase_stock/models/stock.py#L11

So what you should do instead is override the _build_invoice_values_from_pickings method and adjust the invoice in the localization module (writting after create is bad but given this is a per picking manual operation this is still okay).

Or if you feel it can be done quickly in a clean way, extract some _prepare_invoice_from_picking that would contain much of the def _build_invoice_values_from_pickings(self, pickings) code, be called by _build_invoice_values_from_pickings but just return values to _build_invoice_values_from_pickings which would in turn call _simulate_invoice_onchange to create the invoice and would be overridable before the invoice is created.

2020-05-14 20:33 UTC, rvalyi commented
or alternatively you could test hasattr(picking, 'purchase_id') and update the values dictionary only if purchase_id is found. This is often done to avoid the multiplication of glue modules and would be acceptable for me.

2020-05-14 21:01 UTC, rvalyi requested changes

2020-05-14 21:01 UTC, rvalyi commented on stock_picking_invoicing/wizards/stock_invoice_onshipping.py
> +            'purchase_id': picking.purchase_id.id or False,
but of course if you go for the if hasattr(picking, 'purchase_id'), then you should remove this line with picking.purchase_id.id or you will have an error...

2020-05-14 21:01 UTC, rvalyi commented on stock_picking_invoicing/wizards/stock_invoice_onshipping.py
> +            'purchase_line_id': move.purchase_line_id.id or False,
same comment as above

2020-05-14 21:04 UTC, mbcosta commented
Hi @rvalyi , thank you for review. I made the last sugestion "test hasattr(picking, 'purchase_id')" . 

"Indeed, it doesn't depend on purchase nor purchase_stock."  it's true, if should be better make it in the localization, there is no problem for me.

2020-05-14 21:06 UTC, rvalyi requested changes

2020-05-14 21:06 UTC, rvalyi commented on stock_picking_invoicing/wizards/stock_invoice_onshipping.py
> +                'purchase_line_id': move.purchase_line_id.id or False,
can be made simpler as the above suggestion

2020-05-14 21:08 UTC, rvalyi requested changes

2020-05-14 21:08 UTC, rvalyi commented on stock_picking_invoicing/wizards/stock_invoice_onshipping.py
> +                'purchase_id': picking.purchase_id.id or False,
I think this could be written simply as:
```
if hasattr(picking, 'purchase_id'):
    values['purchase_id'] = picking.purchase_id
```
No??

2020-05-20 15:47 UTC, mbcosta commented
Hi @rvalyi @mileo 
Talking with @renatonlima about the implemantation of stock_picking_invoicing in brazilian localization we noticed there is a functionality related to this module, in version 8.0, that maybe should be reimplemented Invoice Policy

Purchase  https://github.com/OCA/OCB/blob/8.0/addons/purchase/res_config.py#L30 
Sale https://github.com/OCA/OCB/blob/8.0/addons/sale_stock/res_config.py#L39 

The initial idea would be create two new modules purchase_stock_picking_invoicing and sale_stock_picking_invocing where we include fields related purchase/sale during the Invoice creation based on Picking and this re implementation. 

What do you think ?

2020-05-20 16:04 UTC, rvalyi commented
Hello Magno, In general, I think adding a "glue module" just because of 1 or 2 fields is a bad idea because it adds a lot of boilerplate code to maintain and think about installing just for 2 or 3 useful lines of code. Then you also tend to create a multiplication of the modules that would depend on these modules...

Instead I think testing for the existence of a field/column like you just did to check if a module is actually installed and if the field should be propagated in some _prepare method is a popular way to fix this kind of situation in the OCA ecosystem. Moreover, sale and purchase are really core Odoo modules generating pickings so we can anticipate their presence in this module without bloating the codebase with extra glue modules.

As for the settings you just mentioned, I would go for adding them in OCA/l10n-brazil/l10n_br_sale_stock and OCA/l10n-brazil/l10n_br_purchase_stock instead of in this repo. The reason is we have more control in OCA/l10n-brazil to merge things faster and this is really where we need them until proven otherwise.

2020-05-20 16:20 UTC, mbcosta commented
I understand your point @rvalyi , we could end up with more README data than code in the modules and maybe the Invoice Policy just matter to brazilian localization.

2020-06-05 22:48 UTC, josepmy commented
Hello @mbcosta, I'm very interested to test it, it's ready?

2020-06-18 15:21 UTC, mbcosta commented
Hi @josepmy , you can test it's ready, we are implement this module in brazilian localization.

2020-06-18 15:43 UTC, josepmy commented
Hi, ok. Let me try.

> El 18 jun 2020, a las 17:21, Magno Barcelo da Costa <notifications@github.com> escribió:
> 
> 
> Hi @josepmy <https://github.com/josepmy> , you can test it's ready, we are implement this module in brazilian localization.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/OCA/account-invoicing/pull/713#issuecomment-646092447>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/ABPMFVQGJARYUJWHIJRIDXLRXIWJFANCNFSM4NA7NEFQ>.
>

2021-01-23 18:44 UTC, marcelsavegnago commented
@mbcosta esta PR está pronta para revisão ? vi que tem uns bloqueios do @rvalyi que acredito que foram tratados.

2021-01-23 21:50 UTC, rvalyi approved these changes
@marcelsavegnago you were right, it's all correct now.
@renatonlima are we not using this already in our projects?

2021-01-30 15:23 UTC, renatonlima approved these changes

2021-01-30 15:35 UTC, renatonlima commented
@rvalyi 

This PR is very important because if you create one invoice based on sale or purchase picking it needs related to sale/purchase line to update some fields like quantity invoiced and others.

@mbcosta KUDOS for your PR!

2021-01-30 15:42 UTC, rvalyi commented
/ocabot merge minor

2021-01-30 16:11 UTC, merged