[12.0][IMP] Consider day_of_the_month in compute()
OCA/account-invoicing pull request #715
Opened 2020-05-19 08:57 UTC by TimLai125

Odoo standard logic in the `compute()` of the `account.payment.term` considers Terms' `day_of_the_month`.
https://github.com/odoo/odoo/blob/6ed05368ab616aa6b256898bcef35fac93dcbb54/addons/account/models/account_invoice.py#L2067-L2069

As `account_payment_term_extension` overwrites the `compute()` of the `account.payment.term` and `day_of_the_month` is no long being considered in the overwritten method. Hence this PR is trying to keep the `compute()` consistent with standard logic.

2020-05-20 03:49 UTC, yostashiro approved these changes
LGTM ;)

This fix makes it possible for us to handle a payment term such as "The end of month after next".

2020-05-20 06:50 UTC, pedrobaeza commented
Please check Travis

2020-05-22 10:46 UTC, kittiu approved these changes

2020-05-24 09:38 UTC, pedrobaeza requested changes
Please add a test exercising the new addition

2020-05-27 15:04 UTC, yostashiro commented on account_payment_term_extension/models/account_payment_term.py
> +                        day=line.day_of_the_month, months=months_delta)
```suggestion
                if line.day_of_the_month > 0:
                    months_delta = (line.months == 0) and (line.day_of_the_month < next_date.day) and 1 or 0
                    next_date += relativedelta(
                        day=line.day_of_the_month, months=months_delta)
```

On second thought, we should bypass the standard month_delta logic when `line.months` is set, since the delta for `line.months` is already taken care of in the previous step.

2023-03-05 12:15 UTC, closed without merging