[11.0][FIX]account_invoice_fiscal_position_update: Keep taxes from pu…
OCA/account-invoicing pull request #718
Opened 2020-05-27 13:10 UTC by javierjcf

…rchase order line when create invoice from smart button

2020-05-27 14:15 UTC, pedrobaeza commented
I think you have both cases: you want to keep the taxes or you screwed up the fiscal position in the purchase order and want to use a new one, so I don't think this patch is valid (or not less than the previous one).

2020-05-28 10:09 UTC, Roodin commented
But if you want to force the change of taxes in a purchase line  i don think that Odoo must change these taxes silently when you create the invoice, ¿no?

2020-05-28 10:16 UTC, pedrobaeza commented
But that should be done on the invoice creation, not on the fiscal position change.

2020-05-28 10:41 UTC, javierjcf commented
Maybe the problem is to get into position change method when creating a invoice from a purchase. The tax is overwrited by this method in the end because an automatic onchange trigger.

If we can avoid to get into this onchange i think this method should contemplate that the invoice line is created from a purchase line with a different tax.

2020-05-28 13:43 UTC, pedrobaeza commented
Which line creating the invoice from the purchase order is triggering that onchange?

2020-05-28 15:34 UTC, javierjcf commented
When i was debugging, i found that this method is called twice. One of them
i think is because of:
 /odoo/odoo/models.py(5068)_onchange_eval()

I don't know how odoo internally manages automatic onchange trigger.

The second time is because of:

account-invoicing/account_invoice_fiscal_position_update/models/account_invoice.py(19)_onchange_partner_id()
self.fiscal_position_change().

I think onchanges are triggered because you are creating the invoice from
an on_chage method in first instance.


El jue., 28 may. 2020 a las 15:43, Pedro M. Baeza (<notifications@github.com>)
escribió:

> Which line creating the invoice from the purchase order is triggering that
> onchange?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/OCA/account-invoicing/pull/718#issuecomment-635358412>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABLELJ6LT4OPVXNNLRU6GCLRTZS7HANCNFSM4NMD32JQ>
> .
>

2020-05-28 17:58 UTC, pedrobaeza requested changes
Thanks for the extra information. Indeed the onchanges are triggered in chain by Odoo itself, but with this suggestion I think we cover both cases:

- Adding the purchase order in the invoice, keeping purchase lines taxes
- Changing the fiscal position on the invoice latter.

Please try to confirm. It would be great to have a test to cover all of this, but maybe it's too much to ask.

2020-05-28 17:58 UTC, pedrobaeza commented on account_invoice_fiscal_position_update/models/account_invoice.py
> +                    if line.purchase_line_id and \
```suggestion
                    if line.invoice_id.purchase_id and line.purchase_line_id and \
```

2020-05-29 11:45 UTC, javierjcf commented
I will try to do the tests soon

2020-05-29 11:48 UTC, pedrobaeza approved these changes
Thanks! Approving although no tests

2020-05-29 11:49 UTC, pedrobaeza requested changes
Oh, wait, there's a basic problem: this module doesn't depend on purchase!! You have to add a new one as glue module.

2020-05-29 12:36 UTC, javierjcf commented
You're right!
I add purchase to manifest and rebased all the PR commits

2020-05-29 12:40 UTC, pedrobaeza commented
Yeah, but that is not valid, as you can't force all the users of this module to install purchase.

You need to create a new `account_invoice_fiscal_position_update_purchase` with this specific code (well, and adaptation with a hook in this one) for being correct. Other "hack" is to test the presence of the fields (`if hasattr(line.invoice_id, 'purchase_id') and ....`) and don't require the dependency and the extra module.

2020-05-29 13:24 UTC, javierjcf commented
I chose the second option. Simpler and not requires to remember you need a
special extra module for this fiscal position update if you are using the
purchase module

El vie., 29 may. 2020 a las 14:40, Pedro M. Baeza (<notifications@github.com>)
escribió:

> Yeah, but that is not valid, as you can't force all the users of this
> module to install purchase.
>
> You need to create a new account_invoice_fiscal_position_update_purchase
> with this specific code (well, and adaptation with a hook in this one) for
> being correct. Other "hack" is to test the presence of the fields (if
> hasattr(line.invoice_id, 'purchase_id') and ....) and don't require the
> dependency and the extra module.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/OCA/account-invoicing/pull/718#issuecomment-635950586>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABLELJ3UMMULUKJCP6SZDJTRT6UMXANCNFSM4NMD32JQ>
> .
>

2020-05-29 15:33 UTC, pedrobaeza commented on account_invoice_fiscal_position_update/models/account_invoice.py
> +                        taxes = line.purchase_line_id.taxes_id
Clarify hack + remove extra useless condition
```suggestion
                    # HACK: using hasattr for not depending on purchase
                    if (hasattr(line.invoice_id, 'purchase_id') and
                            line.invoice_id.purchase_id and
                            line.purchase_line_id.taxes_id):
                        taxes = line.purchase_line_id.taxes_id
```

2020-05-29 17:07 UTC, pedrobaeza approved these changes

2023-03-12 12:14 UTC, closed without merging