[14.0][MIG] account_invoice_transmit_method
OCA/account-invoicing pull request #823
Opened 2020-11-24 18:10 UTC by alexis-via

2021-04-21 12:35 UTC, alexis-via commented
Depends on the migration PR of base_view_inheritance_extension https://github.com/OCA/server-tools/pull/1937

2021-05-21 09:29 UTC, simahawk commented
@alexis-via 2 things:
1. please check the dependency error on OCA/server-tools#1937 so that we can speed it up
2. please squash !fixup commits (even if not yours :wink: )

2021-05-21 09:59 UTC, jcoux requested changes

2021-05-21 09:59 UTC, jcoux commented on account_invoice_transmit_method/models/account_move.py
> +        compute="_compute_transmit_method_domain", default=True
Useless default value.
```suggestion
        compute="_compute_transmit_method_domain"
```

2021-05-21 09:59 UTC, jcoux commented on account_invoice_transmit_method/models/account_move.py
> +        compute="_compute_transmit_method_domain", default=True
Useless default value.
```suggestion
        compute="_compute_transmit_method_domain"
```

2021-05-21 09:59 UTC, jcoux commented on account_invoice_transmit_method/models/account_move.py
> +                    self.partner_id.customer_invoice_transmit_method_id.id or False
No need to set the `.id`, set the record set works too, and no need `or False`: it's already done by the ORM.
```suggestion
                    self.partner_id.customer_invoice_transmit_method_id
```

2021-05-21 09:59 UTC, jcoux commented on account_invoice_transmit_method/models/account_move.py
> +                    self.partner_id.supplier_invoice_transmit_method_id.id or False
No need to set the `.id`, set the record set works too, and no need `or False`: it's already done by the ORM.
```suggestion
                    self.partner_id.supplier_invoice_transmit_method_id
```

2021-06-14 14:33 UTC, patrickrwilson commented
@alexis-via Thanks for your work on this, I've tested and it works well. 

Can you squash all the automated commits (The Translation, [UPD] and .pot) to cleanup the commit history. Once that is done I'll review. Thanks.

2021-06-22 03:39 UTC, TDu approved these changes
LG, thank you for migrating this and its dependencies.
I only see non blocking comments on my side.

2021-06-30 12:13 UTC, qpeyramale commented
LGTM

2021-07-09 21:27 UTC, patrickrwilson commented
@alexis-via just need automated commit history squashed then I will approve.

2021-08-03 09:09 UTC, jcoux approved these changes
Thanks for changes.
My suggestion about `.id or False` have not been addressed, but it's not blocking!
Approved :+1:

2021-08-11 07:20 UTC, simahawk commented
/ocabot merge patch

2021-08-11 07:31 UTC, merged