[MIG] account invoicing mode: Migration to 14.0
OCA/account-invoicing pull request #844
Opened 2021-01-11 14:13 UTC by phuctranerp

This PR includes migration of 3 modules from this PR https://github.com/OCA/account-invoicing/pull/755:
- account_invoice_base_invoicing_mode
- account_invoice_mode_at_shipping
- account_invoice_mode_monthly

2021-03-26 07:14 UTC, fshah-initos commented
Hi @phuctranerp 
Please create seperate PR for other modules we use only one module in a PR.

2021-06-09 09:01 UTC, tarbib commented
Hello @TDu could you please review the PR? cc @jgrandguillaume

2021-06-16 07:07 UTC, TDu commented on account_invoice_mode_at_shipping/models/stock_picking.py
> +        """Check if picking must be invoiced at shippin`g."""
`"""Check if picking must be invoiced at shipping."""`

2021-06-16 07:11 UTC, TDu approved these changes
LG, thanks for the migration.

2021-06-16 07:13 UTC, TDu commented
> Hi @phuctranerp
> Please create seperate PR for other modules we use only one module in a PR.

I think it is good like this in one PR, because they are tightly related.
And this is how they have been proposed for v13.

2021-06-23 15:43 UTC, tarbib commented
@TDu Hello, I just tested it on v14 but there's an issue :
Commercial partner : Company A => invoicing mode : at shipping
Contact : Company A, Contact 1 => accounting tab says that configuration is done on the parent.
If the partner_invoice_id from the SO is a contact then we do not have automatic invoicing at shipping.
The contact should inherit the value from the commercial partner.
Can you please take this case into consideration? cc @jcoux

2021-06-24 13:07 UTC, TDu commented
@tarbib Indeed the fields should be added to the commercial_fields of the res.partner
Something like this on the res.partner model
 ```
@api.model
 def _commercial_fields(self):
          return super()._commercial_fields() + [
              "invoicing_mode",
              "one_invoice_per_order",
          ]                  
```
That would be a good addition to those modules

2021-08-03 07:11 UTC, simahawk requested changes
please rebase (well, replay all commits) on v13.0 as @TDu squashed commits.

2021-08-03 07:15 UTC, simahawk commented
@phuctranerp if you preferer we can merge 13.0 version in 14.0 and make it uninstallable as we've done for postlogistics PR :wink:

2021-08-03 14:44 UTC, simahawk commented
https://github.com/OCA/account-invoicing/pull/983

2021-08-03 14:44 UTC, closed without merging